type SecurityQuery {
  dataInformationClient(dataInformationClientInput: DataInformationClient): dataInformationClient

  validateUserStatus(userStatusInput: userStatusInput): validateUserStatus

  validateSecurity(validateSecurityInput: validateSecurityInput): validateSecurity

  validateBankAccount(validateBankAccountInput: validateBankAccountInput): validateBankAccount

  validatePin(validatePinInput: validatePinInput): validatePin

  getConfigurationVersion(getConfigurationVersionInput: getConfigurationVersionInput): getConfigurationVersion

  getCountry(getCountryInput: getCountryInput): [getCountry]

  catalogTypeIndentification(catalogTypeIndentificationInput: catalogInput): [catalog]

  validateUserExists(validateUserExistsInput: validateUserExistsInput): validateUserExists
}

type dataInformationClient {
  """
  dataInformationClient nombre
  """
  nombre: String!

  """
  dataInformationClient tipoIdentificacion
  """
  tipoIdentificacion: String!

  """
  dataInformationClient Status
  """
  status: Boolean!

  """
  dataInformationClient Message
  """
  message: String!

  """
  dataInformationClient regime
  """
  regimen: dataInformationClientRegime

  """
  dataInformationClient situation
  """
  situacion: dataInformationClientSituation

  """
  dataInformationClient activitiesList
  """
  actividades: [dataInformationClientActivity]
}

type dataInformationClientRegime {
  """
  dataInformationClientRegime codigo
  """
  codigo: Int!

  """
  dataInformationClientRegime descripcion
  """
  descripcion: String!
}

type dataInformationClientSituation {
  """
  dataInformationClientSituation moroso
  """
  moroso: String!

  """
  dataInformationClientSituation omiso
  """
  omiso: String!

  """
  dataInformationClientSituation estado
  """
  estado: String!

  """
  dataInformationClientSituation administracionTributaria
  """
  administracionTributaria: String!
}

type dataInformationClientActivity {
  """
  dataInformationClientActivity estado
  """
  estado: String!

  """
  dataInformationClientActivity tipo
  """
  tipo: String!

  """
  dataInformationClientActivity codigo
  """
  codigo: String!

  """
  dataInformationClientActivity descripcion
  """
  descripcion: String!
}

input DataInformationClient {
  identification: String!

  idBrand: Int!

  user: String!

  tenantId: String

  traceIdentifier: String
}

type validateUserStatus {
  """
  validateUserStatus infoUser
  """
  infoUser: infoUser

  """
  validateUserStatus infoCredit
  """
  infoCredit: infoCredit

  """
  validateUserStatus infoVirtualCard
  """
  infoVirtualCard: infoVirtualCard

  """
  validateUserStatus infoBankAccount
  """
  infoBankAccount: infoBankAccount

  """
  validateUserStatus infoCrypto
  """
  infoCrypto: infoCrypto
}

type infoUser {
  """
  infoUser pkUser
  """
  pkUser: Long!

  """
  infoUser idBrand
  """
  idBrand: Short!

  """
  infoUser fullName
  """
  fullName: String!

  """
  infoUser firstName
  """
  firstName: String!

  """
  infoUser secondName
  """
  secondName: String!

  """
  infoUser lastName
  """
  lastName: String!

  """
  infoUser secondLastName
  """
  secondLastName: String!

  """
  infoUser userName
  """
  userName: String!

  """
  infoUser email
  """
  email: String!

  """
  infoUser phone
  """
  phone: String!

  """
  infoUser birthDate
  """
  birthDate: DateTime

  """
  infoUser idClient
  """
  idClient: Long!

  """
  infoUser VISADirect_ID
  """
  vISADirect_ID: String

  """
  infoUser VISADirect_Usuario
  """
  vISADirect_Usuario: String

  """
  infoUser statusOnfido
  """
  statusOnfido: String

  """
  infoUser fecha_ultimo_acceso
  """
  fecha_ultimo_acceso: DateTime
}

scalar Long

scalar Short

"""
The `DateTime` scalar type represents a date and time. `DateTime` expects timestamps to be formatted in accordance with the [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) standard.
"""
scalar DateTime

type infoCredit {
  """
  infoCredit idClient
  """
  idClient: Long!

  """
  infoCredit idLoanClient
  """
  idLoanClient: Long!

  """
  infoCredit Status
  """
  status: Int!

  """
  infoCredit infoPreApprove
  """
  infoPreApprove: infoCreditPreAprrove
}

type infoCreditPreAprrove {
  """
  infoCreditPreAprrove idUserRequest
  """
  idUserRequest: Long!

  """
  infoCreditPreAprrove status
  """
  status: String!

  """
  infoCreditPreAprrove infoProducts
  """
  infoProducts: [productoPreApprove]

  """
  infoCreditPreAprrove selectedAmount
  """
  selectedAmount: Decimal

  """
  infoCreditPreAprrove statusFirm
  """
  statusFirm: String

  """
  infoCreditPreAprrove currentStep
  """
  currentStep: String
}

type productoPreApprove {
  """
  productoPreApprove idProduct
  """
  idProduct: Int!

  """
  productoPreApprove amountAvailable
  """
  amountAvailable: String!

  """
  productoPreApprove symbolCurrency
  """
  symbolCurrency: String!
}

scalar Decimal

type infoVirtualCard {
  """
  infoVirtualCard Status
  """
  status: Int!
}

type infoBankAccount {
  """
  infoBankAccount StatusFirm
  """
  statusFirm: String

  """
  infoBankAccount IdRequestSysde
  """
  idRequestSysde: Long

  """
  infoBankAccount IdRequestGlobal
  """
  idRequestGlobal: Long

  """
  infoBankAccount Status
  """
  status: Int!
}

type infoCrypto {
  """
  infoCrypto Status
  """
  status: Int!
}

input userStatusInput {
  pkUser: Int!

  identification: String!

  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

type validateSecurity {
  """
  validateSecurity Status
  """
  status: Int

  """
  validateSecurity Message
  """
  message: String

  """
  SendPinProccess Detail
  """
  detail: String
}

input validateSecurityInput {
  pkUser: Int!

  password: String!

  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

type validateBankAccount {
  """
  validateBankAccount responseCode
  """
  responseCode: Int!

  """
  validateBankAccount responseMessage
  """
  responseMessage: String!

  """
  validateBankAccount name
  """
  name: String!

  """
  validateBankAccount currency
  """
  currency: String!

  """
  validateBankAccount sellPriceDollar
  """
  sellPriceDollar: String!

  """
  validateBankAccount buyPriceDollar
  """
  buyPriceDollar: String!

  """
  validateBankAccount bankId
  """
  bankId: Long

  """
  validateBankAccount bankName
  """
  bankName: String
}

input validateBankAccountInput {
  account: String!

  identification: String!

  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

type validatePin {
  """
  validatePin pk_suv_mtr_usuario
  """
  pk_suv_mtr_usuario: String

  """
  validatePin indicador_bloqueo
  """
  indicador_bloqueo: String

  """
  validatePin Status
  """
  status: Int

  """
  validatePin Message
  """
  message: String

  """
  validatePin Detail
  """
  detail: String
}

input validatePinInput {
  idBrand: Int!

  appSource: Int

  pk_User: Int!

  ip: String

  pinSecurity: String!

  telephone: String

  sendValidatePin: String

  flowOrigination: String

  userCreate: String

  tenantId: String

  traceidentifier: String
}

type getConfigurationVersion {
  """
  getConfigurationVersion PK_SUV_PAR_VERSION
  """
  pK_SUV_PAR_VERSION: Int

  """
  getConfigurationVersion FK_SUV_CAT_MARCA
  """
  fK_SUV_CAT_MARCA: Short

  """
  getConfigurationVersion USUARIO_CREACION
  """
  uSUARIO_CREACION: String

  """
  getConfigurationVersion FECHA_CREACION
  """
  fECHA_CREACION: DateTime

  """
  getConfigurationVersion USUARIO_MODIFICACION
  """
  uSUARIO_MODIFICACION: String

  """
  getConfigurationVersion FECHA_MODIFICACION
  """
  fECHA_MODIFICACION: DateTime

  """
  getConfigurationVersion PLATFORM
  """
  pLATFORM: String

  """
  getConfigurationVersion APPVERSION
  """
  aPPVERSION: String

  """
  getConfigurationVersion LLAVE_API_INTERNA
  """
  lLAVE_API_INTERNA: String

  """
  getConfigurationVersion URL_API
  """
  uRL_API: String

  """
  getConfigurationVersion ACTIVA
  """
  aCTIVA: Boolean

  """
  getConfigurationVersion configuracionVersion
  """
  configuracionVersion: configurationVersionObject

  """
  getConfigurationVersion LLAVE_ENCRIPTA
  """
  lLAVE_ENCRIPTA: String

  """
  getConfigurationVersion APP_CONFIG_JSON
  """
  aPP_CONFIG_JSON: String
}

type configurationVersionObject {
  """
  configurationVersionObject EnableAddToAppleWallet
  """
  enableAddToAppleWallet: String

  """
  configurationVersionObject OrigenCrypto
  """
  origenCrypto: String

  """
  configurationVersionObject EnableTransferCrypto
  """
  enableTransferCrypto: String

  """
  configurationVersionObject TimeSesion
  """
  timeSesion: String
}

input getConfigurationVersionInput {
  platform: String!

  appVersion: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

type getCountry {
  """
  getCountry idBrand
  """
  idBrand: Short

  """
  getCountry usuarioCreacion
  """
  usuarioCreacion: String

  """
  getCountry fechaCreacion
  """
  fechaCreacion: DateTime

  """
  getCountry usuarioModificacion
  """
  usuarioModificacion: String

  """
  getCountry fechaModificacion
  """
  fechaModificacion: DateTime

  """
  getCountry nombre
  """
  nombre: String

  """
  getCountry prefijoPais
  """
  prefijoPais: String

  """
  getCountry identificacionTiempoZona
  """
  identificacionTiempoZona: String

  """
  getCountry localizacion
  """
  localizacion: String

  """
  getCountry descripcionPais
  """
  descripcionPais: String
}

input getCountryInput {
  user: String
}

type catalog {
  """
  catalog Pk_Suv_Cat_Catalogo
  """
  pk_Suv_Cat_Catalogo: Short

  """
  catalog Usuario_Creacion
  """
  usuario_Creacion: String

  """
  catalog Fecha_Creacion
  """
  fecha_Creacion: DateTime

  """
  catalog Usuario_Modificacion
  """
  usuario_Modificacion: String

  """
  catalog Fecha_Modificacion
  """
  fecha_Modificacion: DateTime

  """
  catalog Valor
  """
  valor: String

  """
  catalog Descripcion
  """
  descripcion: String

  """
  catalog Formato
  """
  formato: String

  """
  catalog Requiere_Mantenimiento
  """
  requiere_Mantenimiento: Boolean

  """
  catalog Activo
  """
  activo: Boolean
}

input catalogInput {
  idBrand: Int!

  user: String

  llave_Busqueda: String

  tenantId: String

  traceIdentifier: String

  requiere_Mantenimiento: Boolean

  activo: Boolean
}

type validateUserExists {
  """
  userValidation status
  """
  status: Int

  """
  userValidation message
  """
  message: String

  """
  userValidation detail
  """
  detail: String

  """
  userValidation pkUser
  """
  pkUser: String

  """
  userValidation userName
  """
  userName: String

  """
  userValidation email
  """
  email: String

  """
  userValidation phoneNumber
  """
  phoneNumber: String

  """
  userValidation fullName
  """
  fullName: String

  """
  userValidation firstName
  """
  firstName: String

  """
  userValidation secondName
  """
  secondName: String

  """
  userValidation lastName
  """
  lastName: String

  """
  userValidation secondLastName
  """
  secondLastName: String

  """
  userValidation contactMeans
  """
  contactMeans: String

  """
  userValidation nationality
  """
  nationality: String

  """
  userValidation identification
  """
  identification: String

  """
  userValidation countryCode
  """
  countryCode: String

  """
  userValidation currentStep
  """
  currentStep: String

  """
  userValidation userStatus
  """
  userStatus: String
}

input validateUserExistsInput {
  email: String!

  idBrand: Int

  tenantId: String

  traceIdentifier: String
}

type SecurityMutation {
  userValidation(userValidationInput: userValidationInput): userValidation

  updateUserRegister(updateUserRegisterInput: UpdateUserRegister): updateUserRegister

  sendPinProccess(sendPinProccessInput: sendPinProccessInput): SendPinProccess

  onfidoInitialProcess(onfidoInitialProcessInput: OnfidoInitialProcessInput): onfidoInitialProcess

  onfidoCheckProcess(onfidoCheckProcessInputType: onfidoCheckProcessInputType): onfidoCheckProcess

  saveLogTracking(saveLogTrackingInputType: saveLogTrackingInputType): saveLogTracking
}

type userValidation {
  """
  userValidation pkUser
  """
  pkUser: String

  """
  userValidation userName
  """
  userName: String

  """
  userValidation email
  """
  email: String

  """
  userValidation phoneNumber
  """
  phoneNumber: String

  """
  userValidation fullName
  """
  fullName: String

  """
  userValidation firstName
  """
  firstName: String

  """
  userValidation secondName
  """
  secondName: String

  """
  userValidation lastName
  """
  lastName: String

  """
  userValidation secondLastName
  """
  secondLastName: String

  """
  userValidation contactMeans
  """
  contactMeans: String

  """
  userValidation nationality
  """
  nationality: String

  """
  userValidation identification
  """
  identification: String

  """
  userValidation countryCode
  """
  countryCode: String

  """
  userValidation currentStep
  """
  currentStep: String

  """
  userValidation userStatus
  """
  userStatus: String

  """
  userValidation status
  """
  status: Int

  """
  userValidation message
  """
  message: String
}

input userValidationInput {
  email: String!

  currentStep: String!

  idBrand: Int!

  idDocument: Int!

  identification: String!

  firtName: String!

  secondName: String

  firtSurname: String!

  secondSurname: String

  tenantId: String

  traceIdentifier: String
}

type updateUserRegister {
  """
  updateUserRegister pkUser
  """
  pkUser: String

  """
  updateUserRegister userName
  """
  userName: String

  """
  updateUserRegister email
  """
  email: String

  """
  updateUserRegister phoneNumber
  """
  phoneNumber: String

  """
  updateUserRegister fullName
  """
  fullName: String

  """
  updateUserRegister firstName
  """
  firstName: String

  """
  updateUserRegister secondName
  """
  secondName: String

  """
  updateUserRegister lastName
  """
  lastName: String

  """
  updateUserRegister secondLastName
  """
  secondLastName: String

  """
  updateUserRegister contactMeans
  """
  contactMeans: String

  """
  updateUserRegister nationality
  """
  nationality: String

  """
  updateUserRegister identification
  """
  identification: String

  """
  updateUserRegister countryCode
  """
  countryCode: String

  """
  updateUserRegister currentStep
  """
  currentStep: String

  """
  updateUserRegister userStatus
  """
  userStatus: String

  """
  userValidation status
  """
  status: Int

  """
  userValidation message
  """
  message: String
}

input UpdateUserRegister {
  identification: String

  fullName: String

  email: String!

  phoneNumber: String

  firstName: String

  secondName: String

  lastName: String

  secondLastName: String

  pkUser: String!

  userName: String

  contactMeans: String

  nationality: String

  countryCode: String

  currentStep: String!

  activateUser: Boolean

  idBrand: Int!

  user: String!

  tenantId: String

  traceIdentifier: String
}

type SendPinProccess {
  """
  SendPinProccess pk_suv_mtr_usuario
  """
  pk_suv_mtr_usuario: Int

  """
  SendPinProccess correo_electronico
  """
  correo_electronico: String

  """
  SendPinProccess username
  """
  username: String

  """
  SendPinProccess telefono
  """
  telefono: String

  """
  SendPinProccess identificacion
  """
  identificacion: String

  """
  SendPinProccess cantidad_reenvios_pin
  """
  cantidad_reenvios_pin: String

  """
  SendPinProccess cantidad_reenvios_otp
  """
  cantidad_reenvios_otp: String

  """
  SendPinProccess valor_tiempo_exp_pin
  """
  valor_tiempo_exp_pin: String

  """
  SendPinProccess tipo_envio
  """
  tipo_envio: String

  """
  SendPinProccess tipo_envio_sig
  """
  tipo_envio_sig: String

  """
  SendPinProccess Status
  """
  status: Int

  """
  SendPinProccess Message
  """
  message: String

  """
  SendPinProccess Detail
  """
  detail: String
}

input sendPinProccessInput {
  identification: String!

  firstName: String!

  email: String!

  cellphone: String!

  sendMethod: String!

  fk_Suv_Mtr_Usuario: Int!

  idBrand: Int!

  user: String!

  tenantId: String

  traceIdentifier: String
}

type onfidoInitialProcess {
  """
  onfidoInitialProcess applicantId
  """
  applicantId: String!

  """
  onfidoInitialProcess sdkToken
  """
  sdkToken: String!
}

input OnfidoInitialProcessInput {
  names: String!

  lastNames: String!

  identification: String!

  applicationId: String!

  idBrand: Int!

  user: String!

  tenantId: String

  traceIdentifier: String
}

type onfidoCheckProcess {
  """
  onfidoCheckProcess id
  """
  id: String!
}

input onfidoCheckProcessInputType {
  identification: String!

  applicantId: String!

  currentFlow: String!

  pkUser: Int!

  idOnfidoDocumentSdi: String

  idBrand: Int!

  user: String!

  tenantId: String

  traceIdentifier: String

  userRequestId: Int!
}

type saveLogTracking {
  """
  saveLogTracking Status
  """
  status: Int

  """
  saveLogTracking Message
  """
  message: String

  """
  saveLogTracking Detail
  """
  detail: String
}

input saveLogTrackingInputType {
  identification: String!

  pkUser: Int!

  keySearch: String!

  data: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

schema {
  query: SecurityQuery
  mutation: SecurityMutation
}
