type SecurityQuery {
  dataInformationClient(dataInformationClientInput: DataInformationClient): dataInformationClient

  validateSecurity(validateSecurityInput: validateSecurityInput): validateSecurity
}

type dataInformationClient {
  """
  dataInformationClient nombre
  """
  nombre: String!

  """
  dataInformationClient tipoIdentificacion
  """
  tipoIdentificacion: String!

  """
  dataInformationClient Status
  """
  status: Boolean!

  """
  dataInformationClient Message
  """
  message: String!

  """
  dataInformationClient regime
  """
  regimen: dataInformationClientRegime

  """
  dataInformationClient situation
  """
  situacion: dataInformationClientSituation

  """
  dataInformationClient activitiesList
  """
  actividades: [dataInformationClientActivity]
}

type dataInformationClientRegime {
  """
  dataInformationClientRegime codigo
  """
  codigo: Int!

  """
  dataInformationClientRegime descripcion
  """
  descripcion: String!
}

type dataInformationClientSituation {
  """
  dataInformationClientSituation moroso
  """
  moroso: String!

  """
  dataInformationClientSituation omiso
  """
  omiso: String!

  """
  dataInformationClientSituation estado
  """
  estado: String!

  """
  dataInformationClientSituation administracionTributaria
  """
  administracionTributaria: String!
}

type dataInformationClientActivity {
  """
  dataInformationClientActivity estado
  """
  estado: String!

  """
  dataInformationClientActivity tipo
  """
  tipo: String!

  """
  dataInformationClientActivity codigo
  """
  codigo: String!

  """
  dataInformationClientActivity descripcion
  """
  descripcion: String!
}

input DataInformationClient {
  identification: String!

  idBrand: Int!

  user: String!

  tenantId: String

  traceIdentifier: String
}

type validateSecurity {
  """
  validateSecurity Status
  """
  status: Int

  """
  validateSecurity Message
  """
  message: String

  """
  SendPinProccess Detail
  """
  detail: String
}

input validateSecurityInput {
  pkUser: Int!

  password: String!

  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

type SecurityMutation {
  userValidation(userValidationInput: userValidationInput): userValidation

  updateUserRegister(updateUserRegisterInput: UpdateUserRegister): updateUserRegister

  sendPinProccess(sendPinProccessInput: sendPinProccessInput): SendPinProccess

  onfidoInitialProcess(onfidoInitialProcessInput: OnfidoInitialProcessInput): onfidoInitialProcess

  onfidoCheckProcess(onfidoCheckProcessInputType: onfidoCheckProcessInputType): onfidoCheckProcess
}

type userValidation {
  """
  userValidation pkUser
  """
  pkUser: String

  """
  userValidation userName
  """
  userName: String

  """
  userValidation email
  """
  email: String

  """
  userValidation phoneNumber
  """
  phoneNumber: String

  """
  userValidation fullName
  """
  fullName: String

  """
  userValidation firstName
  """
  firstName: String

  """
  userValidation secondName
  """
  secondName: String

  """
  userValidation lastName
  """
  lastName: String

  """
  userValidation secondLastName
  """
  secondLastName: String

  """
  userValidation contactMeans
  """
  contactMeans: String

  """
  userValidation nationality
  """
  nationality: String

  """
  userValidation identification
  """
  identification: String

  """
  userValidation countryCode
  """
  countryCode: String

  """
  userValidation currentStep
  """
  currentStep: String

  """
  userValidation userStatus
  """
  userStatus: String
}

input userValidationInput {
  email: String!

  currentStep: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

type updateUserRegister {
  """
  updateUserRegister pkUser
  """
  pkUser: String

  """
  updateUserRegister userName
  """
  userName: String

  """
  updateUserRegister email
  """
  email: String

  """
  updateUserRegister phoneNumber
  """
  phoneNumber: String

  """
  updateUserRegister fullName
  """
  fullName: String

  """
  updateUserRegister firstName
  """
  firstName: String

  """
  updateUserRegister secondName
  """
  secondName: String

  """
  updateUserRegister lastName
  """
  lastName: String

  """
  updateUserRegister secondLastName
  """
  secondLastName: String

  """
  updateUserRegister contactMeans
  """
  contactMeans: String

  """
  updateUserRegister nationality
  """
  nationality: String

  """
  updateUserRegister identification
  """
  identification: String

  """
  updateUserRegister countryCode
  """
  countryCode: String

  """
  updateUserRegister currentStep
  """
  currentStep: String

  """
  updateUserRegister userStatus
  """
  userStatus: String
}

input UpdateUserRegister {
  identification: String

  fullName: String

  email: String!

  phoneNumber: String

  firstName: String

  secondName: String

  lastName: String

  secondLastName: String

  pkUser: String!

  userName: String

  contactMeans: String

  nationality: String

  countryCode: String

  currentStep: String!

  activateUser: Boolean

  idBrand: Int!

  user: String!

  tenantId: String

  traceIdentifier: String
}

type SendPinProccess {
  """
  SendPinProccess pk_suv_mtr_usuario
  """
  pk_suv_mtr_usuario: Int

  """
  SendPinProccess correo_electronico
  """
  correo_electronico: String

  """
  SendPinProccess username
  """
  username: String

  """
  SendPinProccess telefono
  """
  telefono: String

  """
  SendPinProccess identificacion
  """
  identificacion: String

  """
  SendPinProccess cantidad_reenvios_pin
  """
  cantidad_reenvios_pin: String

  """
  SendPinProccess cantidad_reenvios_otp
  """
  cantidad_reenvios_otp: String

  """
  SendPinProccess valor_tiempo_exp_pin
  """
  valor_tiempo_exp_pin: String

  """
  SendPinProccess Status
  """
  status: Int

  """
  SendPinProccess Message
  """
  message: String

  """
  SendPinProccess Detail
  """
  detail: String
}

input sendPinProccessInput {
  identification: String!

  firstName: String!

  email: String!

  cellphone: String!

  sendMethod: String!

  fk_Suv_Mtr_Usuario: Int!

  idBrand: Int!

  user: String!

  tenantId: String

  traceIdentifier: String
}

type onfidoInitialProcess {
  """
  onfidoInitialProcess applicantId
  """
  applicantId: String!

  """
  onfidoInitialProcess sdkToken
  """
  sdkToken: String!
}

input OnfidoInitialProcessInput {
  names: String!

  lastNames: String!

  identification: String!

  applicationId: String!

  idBrand: Int!

  user: String!

  tenantId: String

  traceIdentifier: String
}

type onfidoCheckProcess {
  """
  onfidoCheckProcess id
  """
  id: String!
}

input onfidoCheckProcessInputType {
  identification: String!

  applicantId: String!

  currentFlow: String!

  pkUser: Int!

  idOnfidoDocumentSdi: String

  idBrand: Int!

  user: String!

  tenantId: String

  traceIdentifier: String
}

schema {
  query: SecurityQuery
  mutation: SecurityMutation
}
