query DataInformationClient($identification:String!, $idBrand:Int!,$user:String!){
    dataInformationClient(
        dataInformationClientInput: {
            identification: $identification
            idBrand: $idBrand
            user: $user
        }
    ) {
        nombre
        tipoIdentificacion
        status
        message
        regimen {
            codigo
            descripcion
        }
        situacion {
            moroso
            omiso
            estado
            administracionTributaria
        }
        actividades {
            estado
            tipo
            codigo
            descripcion
        }
    }
}