package com.multimoney.multimoney.presentation.util.catalog

enum class AdjustEventType(val stgToken: String, val prodToken: String) {
    SPLASH("", ""),

    // ON BOARDING
    ON_BOARDING_1("", ""),
    ON_BOARDING_2("", ""),
    ON_BOARDING_3("", ""),

    // SIGNUP
    SIGNUP_FIRST_BUTTON_CLICKED("", ""),
    SIGNUP_1("", ""),
    SIGNUP_2("", ""),
    SIGNUP_3("", ""),
    SIGNUP_4("", ""),
    SIGNUP_5("", ""),
    SIGNUP_RESEND_OTP("", ""),
    SIGNUP_OTP_API_CALL("", ""),
    SIGNUP_SUCCESS("", ""),
    SIGNUP_ALREADY_BEEN_CUSTOMERS_EMAIL("", ""),
    SIGNUP_ALREADY_BEEN_CUSTOMERS_OTP_EMAIL("", ""),
    SIGNUP_ALREADY_BEEN_CUSTOMERS_OTP_SMS("", ""),
    SIGNUP_ALREADY_BEEN_CUSTOMERS_OTP_SUCCESS_CONFIRMATION("", ""),
    SIGNUP_ALREADY_BEEN_CUSTOMERS_RESEND_OTP("", ""),
    SIGNUP_ALREADY_BEEN_CUSTOMERS_OTP_API_CALL("", ""),
    SIGNUP_ALREADY_BEEN_CUSTOMERS_CREATE_PASSWORD("", ""),

    // LOGIN
    FIRST_LOGIN("", ""),
    LOGIN("", ""),

    // FORGOT
    FORGOT_CONFIRM_EMAIL("", ""),
    FORGOT_CONFIRM_CORRECT_PASSWORD("", ""),
    FORGOT_API_CALL("", ""),
    FORGOT_SUCCESS("", ""),

    // ORIGINATION
    ORIGINATION_OFFER_FIRST_TIME("", ""),
    ORIGINATION_OFFER("", ""),
    ORIGINATION_FIRST_CHECK_TERMS("", ""),
    ORIGINATION_FIRST_ENTER_AMOUNT("", ""),
    ORIGINATION_FIRST_FILL_ACCOUNT("", ""),
    ORIGINATION_FIRST_FILL_MONTHLY_AMOUNT("", ""),
    ORIGINATION_FIRST_FILL_COMPANY_INFORMATION("", ""),
    ORIGINATION_FIRST_FILL_OWN_ADDRESS("", ""),
    ORIGINATION_FIRST_FILL_PEP("", ""),
    ORIGINATION_FIRST_START_ON_FIDO("", ""),
    ORIGINATION_FIRST_ADD_DOCUMENT_ON_FIDO("", ""),
    ORIGINATION_FIRST_FINNISH_ON_FIDO("", ""),
    ORIGINATION_FIRST_FINNISH_EVICERTIA("", ""),
    ORIGINATION_WAIT_SCREEN_EVICERTIA("", ""),
    ORIGINATION_FIRST_CUSTOMER_REJECTED("", ""),
    ORIGINATION_FIRST_CUSTOMER_COMPLETE_REQUEST("", ""),
    ORIGINATION_FIRST_NON_PRE_APPROVED_INFORMATION("", ""),
    ORIGINATION_FIRST_NON_PRE_APPROVED_IS_APPROVED("", ""),
    ORIGINATION_FIRST_NON_PRE_APPROVED_IS_REJECTED("", ""),

    // DISBURSEMENT
    DISBURSEMENT_FIRST_INIT_PROCESS("", ""),
    DISBURSEMENT_FIRST_FINISH_PROCESS_SUCCESS("", ""),

    // CROSSELLING
    CROSSELLING_OFFER_FIRST_TIME("", ""),
    CROSSELLING_OFFER("", ""),
    CROSSELLING_FIRST_CHECK_TERMS("", ""),
    CROSSELLING_FIRST_ENTER_AMOUNT("", ""),
    CROSSELLING_FIRST_FILL_ACCOUNT("", ""),
    CROSSELLING_FIRST_EXTRA_INFORMATION("", ""),
    CROSSELLING_FIRST_FINNISH_EVICERTIA("", ""),
    CROSSELLING_FIRST_CUSTOMER_COMPLETE_REQUEST("", ""),

    // HOME CREDIT
    HOME_CTA_ENABLED_FIRST_AUTOMATIC_PAYMENT("", ""),
    HOME_CTA_FIRST_START_PAYMENT("", ""),
    HOME_CTA_FIRST_REQUEST_ACCOUNT_STATUS("", ""),

    // HOME
    HOME_CTA_FIRST_ACTIVATE_MM_VISA("", ""),

    // MM VISA
    MM_VISA_CTA_FIRST_LINK_MM_VISA("", ""),
    MM_VISA_CTA_FIRST_MM_VISA_ACTIVATED("", ""),

    // SETTINGS
    SETTINGS_CHANGE_EMAIL_SUCCESS("", ""),
    SETTINGS_CHANGE_PHONE_SUCCESS("", ""),
    SETTINGS_CHANGE_PASSWORD_SUCCESS("", ""),
    SETTINGS_FIRST_ADD_ACCOUNT("", ""),
    SETTINGS_USER_WITHOUT_ACCOUNT("", ""),
    SETTINGS_FIRST_ADD_CARD("", ""),
    SETTINGS_USER_WITHOUT_CARD("", ""),
    SETTINGS_CTA_FIRST_START_FLOW_CARD("", ""),
    SETTINGS_CTA_FIRST_FINISH_FLOW_CARD("", ""),
    SETTINGS_CTA_FIRST_VALIDATED_FLOW_CARD("", ""),

    // HOME CRYPTO
    HOME_CRYPTO_FIST_TIME_ENTER_TO_HOME("nkqtow", "elb9ue"),
    HOME_CRYPTO_PAXOS_IN_MAINTENANCE("", ""),

    // PURCHASE CRYPTO
    PURCHASE_CRYPTO_FIRST_TIME_PRESS_BUY_BUTTON("b1ww5c", "4ne0lu"),
    PURCHASE_CRYPTO_FIRST_TIME_SUCCESS_PURCHASE("a5ohj7", "b79ays"),

    // SELL CRYPTO
    SELL_CRYPTO_FIRST_TIME_PRESS_SELL_BUTTON("b863zi", "b79ays"),
    SELL_CRYPTO_FIRST_TIME_SUCCESS_SELL("wwz72o", "vvm693"),

    // SEND CRYPTO
    SEND_CRYPTO_FIRST_TIME_PRESS_SEND_BUTTON("477ggy", "rqvkuq"),
    SEND_CRYPTO_FIRST_TIME_SUCCESS_SEND("us6gm5", "kukvye"),

    // RECEIVE CRYPTO
    RECEIVE_CRYPTO_FIRST_TIME_PRESS_RECEIVE_BUTTON("vmqdy2", "vvj95q"),
    RECEIVE_CRYPTO_PRESS_SHARE_BUTTON("", ""),
    RECEIVE_CRYPTO_ENTER_QR_SCREEN("", "")
}
