package com.multimoney.multimoney.presentation.util.catalog

enum class QuickActionFlow(val flow : String) {
    DISBURSE_AVAILABLE ("DESEMBOLSAR_DISPONIBLE"),
    PAY_FEE("PAGAR_CUOTA"),
    ACTIVATE_MM_VISA("ACTIVAR_MULTIMONEY_VISA"),
    SEE_MM_VISA("VER_DATOS_MULTIMONEY_VISA"),
    PAY_AT_BUSINESS("PAGAR_EN_COMERCIO"),
    SAVE_SMART("AHORRAR_SMART"),
    SEND_MONEY("ENVIAR_DINERO"),
    BUY_CRYPTO("COMPRAR_CRIPTO"),
    SELL_CRYPTO("VENDER_CRIPTO"),
    RECEIVE_CRYPTO("RECIBIR_CRIPTO"),
    SEND_CRYPTO("ENVIAR_CRIPTO")
}