buildscript {
    apply from: 'dependencies.gradle'
    repositories {
        maven {
            // For the DexGuard Gradle plugin jar.
            credentials {
                username = System.env.DEXGUARD_USERNAME ? "${System.env.DEXGUARD_USERNAME}" : dexGuardUserName
                password = System.env.DEXGUARD_PASSWORD ? "${System.env.DEXGUARD_PASSWORD}" : dexGuardPassword
            }
            url "https://maven.guardsquare.com"
            // Only search for artifacts with groupId "com.guardsquare.*",
            // supported since gradle 5.1.
            content {
                includeGroupByRegex "com\\.guardsquare.*"
            }
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
    dependencies {
        classpath hilt.plugin
        classpath firebase.perf_classpath
        classpath firebase.crashlytics_classpath
        classpath google_services.plugin
        classpath dexguard.classpath
        classpath appLanga.app_langa_classpath
    }
}// Top-level build file where you can add configuration options common to all sub-projects/modules.

plugins {
    id 'com.android.application' version '7.1.0' apply false
    id 'com.android.library' version '7.1.0' apply false
    id 'org.jetbrains.kotlin.android' version '1.8.0' apply false
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

task setupReactIntegration(type: Exec) {
    def command = 'sh'
    if (org.gradle.internal.os.OperatingSystem.current() == org.gradle.internal.os.OperatingSystem.WINDOWS) {
        command = "C:/Program Files/Git/bin/bash.exe"
    }
    commandLine command, "$rootDir/checkReactModules.sh"
}
