pluginManagement {
    repositories {
//        maven {
//            url '../DexGuard-9.3.1'          // For the DexGuard plugin.
//        }
        gradlePluginPortal()
        google()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
rootProject.name = "Multimoney"
include ':app'
include ':domain'
include ':data'
