pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        maven { url 'https://maven.applanga.com/' }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.applanga.com/' }
        maven { url 'https://jitpack.io' }
        maven {
            url "https://nexus-public.novopayment.net/repository/maven-public/"
            credentials {
                username = novoDependencyUser
                password = novoDependencyPassword
            }
        }
    }
}
rootProject.name = "Multimoney"
include ':app'
include ':domain'
include ':data'
