package com.multimoney.data.mapper.smartaccount

import com.multimoney.data.networking.accountsmart.apollomodel.GeneralEconomicActivityQuery
import com.multimoney.domain.model.accountsmart.GeneralEconomicActivity
import com.multimoney.domain.model.accountsmart.GeneralEconomicActivityResult

/**
 * A mapper class to transform all query result data from the autogenerated class
 * "GeneralEconomicActivityQuery" to the domain model that will be used in the
 * UI components from the presentation layer.
 */
private fun GeneralEconomicActivityQuery.Result.mapToDomain() =
    GeneralEconomicActivity(
        id = id,
        iconCode = iconCode.toInt(),
        description = descripcion
    )

private fun GeneralEconomicActivityQuery.GeneralEconomicActivity.mapToDomain() =
    GeneralEconomicActivityResult(
        resultList = result?.map { it?.mapToDomain() } ?: listOf()
    )

fun GeneralEconomicActivityQuery.Data.mapToDomain() = generalEconomicActivity?.mapToDomain()
