package com.multimoney.data.mapper.smartaccount

import com.multimoney.data.networking.graphql.apollomodel.GeneralEconomicActivityQuery
import com.multimoney.domain.model.accountsmart.GeneralEconomicActivity
import com.multimoney.domain.model.accountsmart.GeneralEconomicActivityResult

/**
 * A mapper class to transform all query result data from the autogenerated class
 * "GeneralEconomicActivityQuery" to the domain model that will be used in the
 * UI components from the presentation layer.
 */
private fun GeneralEconomicActivityQuery.Result.mapToDomainModel() =
    GeneralEconomicActivity(
        id = id ?: 0,
        iconCode = iconCode?.toInt(),
        description = descripcion
    )

private fun GeneralEconomicActivityQuery.GeneralEconomicActivity.mapToDomainModel() =
    GeneralEconomicActivityResult(
        resultList = result.map { it.mapToDomainModel() }
    )

fun GeneralEconomicActivityQuery.Data.mapToDomainModel() = generalEconomicActivity?.mapToDomainModel()
