mutation CardBlockingNV($blockType: String!, $observations: String!, $clientId: Int!, $userApp: String!,$cardToken: String!,$source: String!,$idLoan: Int!,$user: String!,$idBrand: Int!){
    cardBlockingNV(
        cardBlockingNVInput: {
            blockType: $blockType
            observations: $observations
            clientId: $clientId
            userApp: $userApp
            cardToken: $cardToken
            source: $source
            idPrestamo: $idLoan
            user: $user
            idBrand: $idBrand
        }
    ) {
        processedAt
    }
}