mutation CreateUserVD(
    $identification: String!,
    $firstName: String!,
    $secondName: String!,
    $lastName: String!,
    $secondLastName: String!,
    $email: String!,
    $callerId: String!,
    $user: String!,
    $idBrand: Int!,
    $accountToken: Long!
)
{
    createUserVD(
        createUserVDInput: {
            identification: $identification,
            firstName: $firstName,
            secondName: $secondName,
            lastName: $lastName,
            secondLastName: $secondLastName,
            email: $email,
            callerId: $callerId,
            user: $user,
            idBrand: $idBrand
            accountToken: $accountToken
        }
    ) {
        userName
        password
    }
}