query BalanceCardInformation(
    $user: String!,
    $identification: String!,
    $idBrand: Int!,
    $idClient: Long!,
    $idLoanClient: Int!,
    $cardStatus: Int!
){
    balanceCardInformation(
            balanceCardInformationInput: {
                idClient: $idClient
                identification: $identification
                idLoanClient: $idLoanClient
                user: $user
                idBrand: $idBrand
                status: $cardStatus
            }
        ) {
            cardInfo {
                cardToken
                cardNumber
                expDate
                holderName
                status
                blockType
                cvalidation
                type
            }
            sALDO_FLOTANTE
            pERMITE_DESBLOQUEO
            eSTADO
            cOMISION_DESEMBOLSO
            tASA_INTERES
            pLAZO
            nOMBRE_COMPLETO
            rEMISION
        }
}