type BalanceQuery {
  balanceCredit(balanceCreditInput: balanceCreditInput): [balanceCredit]

  balanceAccountSmart(checkAccountInput: checkAccountInput): CheckAccount

  balanceCryptoAccount(balanceCryptoInput: balanceCryptoInput): balanceCryptoAccount

  balanceCardInformation(balanceCardInformationInput: balanceCardInformationInput): balanceCardInformation
}

type balanceCredit {
  """
  balanceCredit Fk_Suv_Cat_Marca
  """
  fk_Suv_Cat_Marca: Short!

  """
  balanceCredit Id_Prestamo
  """
  id_Prestamo: Long!

  """
  balanceCredit Pagare
  """
  pagare: String!

  """
  balanceCredit Saldo_Actual
  """
  saldo_Actual: Decimal!

  """
  balanceCredit Moneda
  """
  moneda: String!

  """
  balanceCredit Resumen
  """
  resumen: [balanceCreditResume]

  """
  balanceCredit limite_credito
  """
  limite_credito: String!

  """
  balanceCredit limite_credito_label
  """
  limite_credito_label: String!

  """
  balanceCredit aplicaAumentoLinea
  """
  aplicaAumentoLinea: Boolean!

  """
  balanceCredit tasa_interes
  """
  comision_desembolso: String!

  """
  balanceCredit tasa_interes
  """
  tasa_interes: String!

  """
  balanceCredit plazo
  """
  plazo: String!

  """
  balanceCredit desc_producto
  """
  desc_producto: String!

  """
  balanceCredit saldo_monto_cancelar
  """
  saldo_monto_cancelar: Decimal!

  """
  balanceCredit id_Producto_Principal
  """
  id_Producto_Principal: Short!

  """
  balanceCredit Moneda_Default
  """
  moneda_Default: String!

  """
  balanceCredit Compra_Dolares
  """
  compra_Dolares: Decimal!

  """
  balanceCredit Venta_Dolares
  """
  venta_Dolares: Decimal!

  """
  balanceCredit Orden_Presentacion
  """
  orden_Presentacion: Int!

  """
  balanceCredit Ciclo
  """
  puede_Ampliar: Boolean!

  """
  balanceCredit Micro_Credito
  """
  micro_Credito: Boolean
}

scalar Short

scalar Long

scalar Decimal

type balanceCreditResume {
  """
  balanceCreditResume Ciclo
  """
  ciclo: Short!

  """
  balanceCreditResume Saldo_Actual
  """
  saldo_Actual: Decimal!

  """
  balanceCreditResume Saldo_Actual_Label
  """
  saldo_Actual_Label: String!

  """
  balanceCreditResume Saldo_Anterior
  """
  saldo_Anterior: Decimal!

  """
  balanceCreditResume Saldo_Intereses
  """
  saldo_Intereses: Decimal!

  """
  balanceCreditResume Cargo_Gestion
  """
  cargo_Gestion: Decimal!

  """
  balanceCreditResume Monto_Vencido
  """
  monto_Vencido: Decimal!

  """
  balanceCreditResume Saldo_Disponible
  """
  saldo_Disponible: Decimal!

  """
  balanceCreditResume Saldo_Disponible_Label
  """
  saldo_Disponible_Label: String!

  """
  balanceCreditResume Moneda
  """
  moneda: String!

  """
  balanceCreditResume Pago_Minimo
  """
  pago_Minimo: Decimal!

  """
  balanceCreditResume Pago_Minimo_Label
  """
  pago_Minimo_Label: String!

  """
  balanceCreditResume Pagos_Vencidos
  """
  pagos_Vencidos: Int!

  """
  balanceCreditResume Fec_Pago
  """
  fec_Pago: DateTime!

  """
  balanceCreditResume Estado_Pagare
  """
  fecha_Pago_Label: String!

  """
  balanceCreditResume Estado_Pagare
  """
  estado_Pagare: Boolean!

  """
  balanceCreditResume Estado_Ampli
  """
  estado_Ampli: Boolean!

  """
  balanceCreditResume Interes_Mensual
  """
  interes_Mensual: String!

  """
  balanceCreditResume Gasto_Formalizacion
  """
  gasto_Formalizacion: String!

  """
  balanceCreditResume Mensaje_Cuota
  """
  mensaje_Cuota: String!

  """
  balanceCreditResume Cargos_Mora
  """
  estado_Cargo_Auto: Boolean!

  """
  balanceCreditResume Cargos_Mora
  """
  cargos_Mora: Decimal!

  """
  balanceCreditResume Cargos_Mora_Label
  """
  cargos_Mora_Label: String!

  """
  balanceCreditResume Ampli_Pendiente
  """
  ampli_Pendiente: Boolean!

  """
  balanceCreditResume Cuota_Mensual
  """
  cuota_Mensual: Decimal!

  """
  balanceCreditResume Cuota_Mensual_Label
  """
  cuota_Mensual_Label: String!

  """
  balanceCreditResume Dias_Vencidos
  """
  dias_Vencidos: Int!

  """
  balanceCreditResume Producto_Activo
  """
  producto_Activo: Boolean!

  """
  balanceCreditResume Cuenta_Iban
  """
  cuenta_Iban: String!

  """
  balanceCreditResume Aplica_Debito_Aut
  """
  aplica_Debito_Aut: Boolean!

  """
  balanceCreditResume Debito_Aut_Activo
  """
  debito_Aut_Activo: Boolean!

  """
  balanceCreditResume VDDebito_Aut_Activo
  """
  vDDebito_Aut_Activo: Boolean!

  """
  balanceCreditResume Aplica_Crear_Tarjeta
  """
  aplica_Crear_Tarjeta: Boolean!

  """
  balanceCreditResume Disponible
  """
  disponible: Decimal!

  """
  balanceCreditResume Disponible_Compra
  """
  disponible_Compra: Decimal!

  """
  balanceCreditResume Id_Producto
  """
  id_Producto: Int!

  """
  balanceCreditResume Abreviatura_Moneda
  """
  abreviatura_Moneda: String!

  """
  balanceCreditResume Saldo_Monto_Cancelar
  """
  saldo_Monto_Cancelar: Decimal!

  """
  balanceCreditResume Id_Moneda
  """
  id_Moneda: Int!

  """
  balanceCreditResume Aplica_Ampli_Comercio
  """
  aplica_Ampli_Comercio: Boolean!
}

"""
The `DateTime` scalar type represents a date and time. `DateTime` expects timestamps to be formatted in accordance with the [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) standard.
"""
scalar DateTime

input balanceCreditInput {
  idClient: Int!

  status: Int!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

type CheckAccount {
  """
  CheckAccount Accounts
  """
  accounts: [Accounts]

  """
  CheckAccount Request
  """
  request: Request
}

type Accounts {
  """
  Accounts Accounts
  """
  code: String!

  """
  Accounts Request
  """
  message: String!

  """
  Accounts TotalBalance
  """
  totalBalance: Decimal!

  """
  Accounts AverageBalance
  """
  averageBalance: Decimal!

  """
  Accounts AccountNumber
  """
  accountNumber: String!

  """
  Accounts TokenNumber
  """
  tokenNumber: String!

  """
  Accounts ProductDescription
  """
  productType: String!

  """
  Accounts CurrencyCode
  """
  currencyCode: String!

  """
  Accounts Email
  """
  email: String!

  """
  Accounts PhoneNumber
  """
  phoneNumber: String!

  """
  Accounts AccountStatus
  """
  accountStatus: Int!

  """
  Accounts CustomerId
  """
  customerId: Long!

  """
  Accounts GainedInterest
  """
  gainedInterest: Decimal!

  """
  Accounts ActiveBroker
  """
  activeBroker: Boolean!

  """
  Accounts IbanAccountNumber
  """
  ibanAccountNumber: String!

  """
  Accounts IdCurrencyAccount
  """
  idCurrencyAccount: Long!

  """
  Accounts FullNameCustomer
  """
  fullNameCustomer: String!

  """
  Accounts VisaDirectId
  """
  visaDirectId: String!

  """
  Accounts VisaDirectUser
  """
  visaDirectUser: String!
}

type Request {
  """
  Request StatusFirm
  """
  statusFirm: String

  """
  Request StatusOnfido
  """
  statusOnfido: String

  """
  Request IdRequestSysde
  """
  idRequestSysde: Long!

  """
  Request IdRequestGlobal
  """
  idRequestGlobal: Long!
}

input checkAccountInput {
  identification: String!

  status: Int!

  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

type balanceCryptoAccount {
  """
  balanceCryptoAccount globalBalance
  """
  globalBalance: Decimal!

  """
  balanceCryptoAccount investedBalance
  """
  investedBalance: String!

  """
  balanceCryptoAccount percentageInvested
  """
  percentageInvested: String!

  """
  balanceCryptoAccount items
  """
  items: [balaceCryptoAccountItem]
}

type balaceCryptoAccountItem {
  """
  balaceCryptoAccountItem asset
  """
  asset: String!

  """
  balaceCryptoAccountItem available
  """
  available: Decimal!

  """
  balaceCryptoAccountItem trading
  """
  trading: String!

  """
  balaceCryptoAccountItem descriptionCurrency
  """
  descriptionCurrency: String!

  """
  balaceCryptoAccountItem balanceDollars
  """
  balanceDollars: Decimal!

  """
  balaceCryptoAccountItem investedBalanceCurrency
  """
  investedBalanceCurrency: String!

  """
  balaceCryptoAccountItem percentageInvestedCurrency
  """
  percentageInvestedCurrency: String!

  """
  balaceCryptoAccountItem priceOfTheDay
  """
  priceOfTheDay: Decimal!

  """
  balaceCryptoAccountItem url_image
  """
  url_image: String!
}

input balanceCryptoInput {
  identification: String!

  assets: String

  status: Int!

  idBrand: Int!

  user: String!

  tenantId: String

  traceIdentifier: String
}

type balanceCardInformation {
  """
  balanceCardInformation rc
  """
  rc: String!

  """
  balanceCardInformation msg
  """
  msg: String!

  """
  balanceCardInformation cardInfo
  """
  cardInfo: balanceCardInfoItem

  """
  balanceCardInformation SALDO_FLOTANTE
  """
  sALDO_FLOTANTE: String

  """
  balanceCardInformation PERMITE_DESBLOQUEO
  """
  pERMITE_DESBLOQUEO: Boolean!

  """
  balanceCardInformation COMISION_DESEMBOLSO
  """
  cOMISION_DESEMBOLSO: String

  """
  balanceCardInformation TASA_INTERES
  """
  tASA_INTERES: String

  """
  balanceCardInformation PLAZO
  """
  pLAZO: String

  """
  balanceCardInformation NOMBRE_COMPLETO
  """
  nOMBRE_COMPLETO: String

  """
  balanceCardInformation ESTADO
  """
  eSTADO: String

  """
  balanceCardInformation REMISION
  """
  rEMISION: Boolean!
}

type balanceCardInfoItem {
  """
  balanceCardInfoItem cardToken
  """
  cardToken: String!

  """
  balanceCardInfoItem cardNumber
  """
  cardNumber: String

  """
  balanceCardInfoItem expDate
  """
  expDate: String

  """
  balanceCardInfoItem holderName
  """
  holderName: String

  """
  balanceCardInfoItem status
  """
  status: String

  """
  balanceCardInfoItem blockType
  """
  blockType: String

  """
  balanceCardInfoItem cvalidation
  """
  cvalidation: String

  """
  balanceCardInfoItem type
  """
  type: String
}

input balanceCardInformationInput {
  idClient: Int!

  identification: String!

  idLoanClient: Int!

  status: Int!

  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

schema {
  query: BalanceQuery
}
