plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'dagger.hilt.android.plugin'
    id 'kotlin-kapt'
    id 'com.google.firebase.firebase-perf'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
}

apply from: '../dependencies.gradle'

android {
    compileSdk compile_sdk_version

    defaultConfig {
        applicationId "com.multimoney.multimoney"
        minSdk min_sdk_version
        targetSdk target_sdk_version
        versionCode version_code
        versionName version_name

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }

        buildConfigField "String", "APP_ENVIRONMENT", System.env.APP_ENVIRONMENT ? "\"${System.env.APP_ENVIRONMENT}\"" : appEnvironment
    }

    buildTypes {
        production {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            buildConfigField "String", "SENTRY_DSN", System.env.PRODUCTION_SENTRY_DSN ? "\"${System.env.PRODUCTION_SENTRY_DSN}\"" : sentryDsn
            buildConfigField "String", "ONFIDO_API_TOKEN", System.env.PRODUCTION_ONFIDO_API_TOKEN ? "\"${System.env.PRODUCTION_ONFIDO_API_TOKEN}\"" : onfidoApiToken
            buildConfigField "String", "ADJUST_APP_TOKEN", System.env.PRODUCTION_ADJUST_APP_TOKEN ? "\"${System.env.PRODUCTION_ADJUST_APP_TOKEN}\"" : ajustAppToken
        }
        staging {
            applicationIdSuffix ".staging"
            testCoverageEnabled true
            buildConfigField "String", "SENTRY_DSN", System.env.STAGING_SENTRY_DSN ? "\"${System.env.STAGING_SENTRY_DSN}\"" : sentryDsn
            buildConfigField "String", "ONFIDO_API_TOKEN", System.env.STAGING_ONFIDO_API_TOKEN ? "\"${System.env.STAGING_ONFIDO_API_TOKEN}\"" : onfidoApiToken
            buildConfigField "String", "ADJUST_APP_TOKEN", System.env.STAGING_ADJUST_APP_TOKEN ? "\"${System.env.STAGING_ADJUST_APP_TOKEN}\"" : ajustAppToken
        }
        debug {
            applicationIdSuffix ".dev"
            testCoverageEnabled true
            buildConfigField "String", "SENTRY_DSN", System.env.DEVELOPMENT_SENTRY_DSN ? "\"${System.env.DEVELOPMENT_SENTRY_DSN}\"" : sentryDsn
            buildConfigField "String", "ONFIDO_API_TOKEN", System.env.DEVELOPMENT_ONFIDO_API_TOKEN ? "\"${System.env.DEVELOPMENT_ONFIDO_API_TOKEN}\"" : onfidoApiToken
            buildConfigField "String", "ADJUST_APP_TOKEN", System.env.DEVELOPMENT_ADJUST_APP_TOKEN ? "\"${System.env.DEVELOPMENT_ADJUST_APP_TOKEN}\"" : ajustAppToken
        }
    }
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion compose_version
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }

    splits {
        abi {
            enable true
            reset()
            include 'x86', 'x86_64', 'arm64-v8a', 'armeabi-v7a'
            universalApk false
        }
    }
}

dependencies {

    implementation project(path: ':data')
    implementation project(path: ':domain')

    // Common
    implementation common.core_ktlx

    // Google Services
    implementation google_services.ads

    // Activity
    implementation activity.compose

    // Lifecycle
    implementation lifecycle.runtime
    kapt lifecycle.compiler
    implementation lifecycle.view_model
    implementation lifecycle.view_model_compose
    implementation lifecycle.view_model_saved_state

    // Navigation
    implementation navigation.compose
    androidTestImplementation navigation.test

    // Compose
    implementation compose.ui
    implementation compose.material
    debugImplementation compose.tooling
    implementation compose.foundation
    implementation compose.livedata
    androidTestImplementation compose.test

    // Hilt
    implementation hilt.android
    kapt hilt.compiler
    implementation hilt.navigation

    // Coroutines
    implementation coroutines.android

    // Preferences
    implementation preferences.data_store

    // Chart
    implementation chart.mp_android_chart

    // Firebase
    implementation platform(firebase.bom)
    implementation firebase.config
    implementation firebase.perf
    implementation firebase.dynamic_links
    implementation firebase.messaging
    implementation firebase.crashlytics
    implementation firebase.analytics
    implementation firebase.installations

    // OnFido
    implementation onfido.capture

    // Adjust
    implementation adjust.android
    implementation adjust.webbridge
    implementation adjust.installreferrer

    // Lottie
    implementation lottieDependency.lottie

    // Cognito
    implementation cognito.core
    implementation cognito.auth

    // Desugar
    coreLibraryDesugaring desugar.jdk

    // Common Test
    testImplementation common_test.junit
    androidTestImplementation common_test.ext_junit
    androidTestImplementation common_test.espresso
    testImplementation common_test.robolectric
    testImplementation common_test.mockito_core
}