plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'dagger.hilt.android.plugin'
    id 'com.google.firebase.firebase-perf'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
    id 'dexguard'
    id 'applanga'
    id 'kotlin-kapt'
}
apply from: '../dependencies.gradle'

android {
    compileSdk compile_sdk_version

    def getVersionCode = { ->
        def isBitrise = System.getenv("BITRISE_BUILD_NUMBER") != null;

        if (isBitrise) {
            try {
                def bitriseBuildNumber = Integer.parseInt(System.getenv("BITRISE_BUILD_NUMBER"))
                return bitriseBuildNumber
            } catch (e) {
                // ignore
            }
        }
        return 1 // default
    }

    defaultConfig {
        applicationId "com.multimoney.multimoney"
        minSdk min_sdk_version
        targetSdk target_sdk_version
        versionCode getVersionCode()
        versionName System.getenv("VERSION_NAME") ? String.valueOf(System.getenv("VERSION_NAME")) : versionNameDebug

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }

        buildConfigField "String", "APP_ENVIRONMENT", System.env.APP_ENVIRONMENT ? "\"${System.env.APP_ENVIRONMENT}\"" : appEnvironment
    }

    buildTypes {
        production {
            minifyEnabled false
            shrinkResources false
            applicationIdSuffix ".cr"
            buildConfigField "String", "SENTRY_DSN", System.env.PRODUCTION_SENTRY_DSN ? "\"${System.env.PRODUCTION_SENTRY_DSN}\"" : sentryDsn
            buildConfigField "String", "ONFIDO_API_TOKEN", System.env.PRODUCTION_ONFIDO_API_TOKEN ? "\"${System.env.PRODUCTION_ONFIDO_API_TOKEN}\"" : onfidoApiToken
            buildConfigField "String", "ADJUST_APP_TOKEN", System.env.PRODUCTION_ADJUST_APP_TOKEN ? "\"${System.env.PRODUCTION_ADJUST_APP_TOKEN}\"" : adjustAppToken
        }
        staging {
            applicationIdSuffix ".dev"
            testCoverageEnabled true
            buildConfigField "String", "SENTRY_DSN", System.env.STAGING_SENTRY_DSN ? "\"${System.env.STAGING_SENTRY_DSN}\"" : sentryDsn
            buildConfigField "String", "ONFIDO_API_TOKEN", System.env.STAGING_ONFIDO_API_TOKEN ? "\"${System.env.STAGING_ONFIDO_API_TOKEN}\"" : onfidoApiToken
            buildConfigField "String", "ONFIDO_APPLICATION_ID",  onfidoApplicationId
            buildConfigField "String", "ADJUST_APP_TOKEN", System.env.STAGING_ADJUST_APP_TOKEN ? "\"${System.env.STAGING_ADJUST_APP_TOKEN}\"" : adjustAppToken
            signingConfig signingConfigs.debug
        }
        debug {
            applicationIdSuffix ".dev"
            testCoverageEnabled true
            buildConfigField "String", "SENTRY_DSN", System.env.DEVELOPMENT_SENTRY_DSN ? "\"${System.env.DEVELOPMENT_SENTRY_DSN}\"" : sentryDsn
            buildConfigField "String", "ONFIDO_API_TOKEN", System.env.DEVELOPMENT_ONFIDO_API_TOKEN ? "\"${System.env.DEVELOPMENT_ONFIDO_API_TOKEN}\"" : onfidoApiToken
            buildConfigField "String", "ONFIDO_APPLICATION_ID",  onfidoApplicationId
            buildConfigField "String", "ADJUST_APP_TOKEN", System.env.DEVELOPMENT_ADJUST_APP_TOKEN ? "\"${System.env.DEVELOPMENT_ADJUST_APP_TOKEN}\"" : adjustAppToken
        }
    }
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
        freeCompilerArgs += "-Xopt-in=kotlin.RequiresOptIn"
    }
    buildFeatures {
        compose true
    }
    composeOptions {
        kotlinCompilerExtensionVersion compose_compiler_version
    }
    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

kapt {
    correctErrorTypes true
}

dependencies {

    implementation project(path: ':data')
    implementation project(path: ':domain')

    // Common
    implementation common.core_ktlx

    // Google Services
    implementation google_services.ads
    implementation google_services.auth
    implementation google_services.auth_api_phone
    implementation google_services.tag_manager

    // Activity
    implementation activity.compose

    // Lifecycle
    implementation lifecycle.runtime
    kapt lifecycle.compiler
    implementation lifecycle.view_model
    implementation lifecycle.view_model_compose
    implementation lifecycle.view_model_saved_state

    // Navigation
    implementation navigation.compose
    androidTestImplementation navigation.test

    // Compose
    implementation compose.ui
    implementation compose.util
    implementation compose.material
    implementation compose.tooling
    implementation compose.foundation
    implementation compose.livedata
    androidTestImplementation compose.test
    implementation compose.extended_icons
    implementation compose.coil

    // Hilt
    implementation hilt.android
    kapt hilt.compiler
    implementation hilt.navigation
    implementation hilt.common
    implementation hilt.work

    // Work Manager
    implementation work_manager.runtime

    // Coroutines
    implementation coroutines.android

    // Chart
    implementation chart.mp_android_chart

    // Firebase
    implementation platform(firebase.bom)
    implementation firebase.config
    implementation firebase.perf
    implementation firebase.dynamic_links
    implementation firebase.messaging
    implementation firebase.crashlytics
    implementation firebase.analytics
    implementation firebase.installations

    // OnFido
    implementation onfido.capture

    // Adjust
    implementation adjust.android
    implementation adjust.webbridge
    implementation adjust.installreferrer

    // Lottie
    implementation lottieDependency.lottie

    // Desugar
    coreLibraryDesugaring desugar.jdk

    // Togisoft
    implementation togisoft.country_code_picker

    // LibPhoneNumber
    implementation libphonenumber.libphonenumber

    // AppLanga
    implementation appLanga.app_langa

    // Biometric
    implementation biometric.biometric

    //Accompanist
    implementation accompanist.flowlayout
    implementation accompanist.pager
    implementation accompanist.pager_indicator
    implementation accompanist.system_ui_controller

    // Constraint Layout
    implementation constraint_layout.compose

    // Shimmer
    implementation shimmer.shimmer

    //httmText
    implementation htmlText.htmlText

    // Slider
    implementation slider.slider

    // VISA
    implementation appcompat.appcompat
    implementation visa.visa

    // Common Test
    testImplementation common_test.junit
    androidTestImplementation common_test.ext_junit
    androidTestImplementation common_test.espresso
    testImplementation common_test.robolectric
    testImplementation common_test.mockito_core

    // Paging
    implementation paging3.paging3_runtime
    implementation paging3.paging3_compose

    // Novo
    debugImplementation(novo.novo_dev) {
        exclude group: "com.novopayment.sdk.android", module: "visa-sensory-branding"
    }

    productionImplementation novo.novo_prod

}

dexguard {

    version = dexguard_version

    // Keep the license secure in your CD/CI
    license = "../dexguard-license.txt"

    configurations {
        production {
            defaultConfiguration 'dexguard-release-aggressive.pro'
            configuration 'dexguard-project.txt'
            configuration 'proguard-project.txt'
        }
    }
}