mutation ManageSinpeAccountSave(
    $user: String,
    $idBrand: Int,
    $identification: String,
    $account_number: String,
    $id_Currency: Long,
    $nameAccount: String,
    $country: String,
    $id_account: Long,
    $isFavorite: Boolean,
    $option: String
    $idBank: Long,
    $typeAccount:Int
){
    manageSinpeAccountSave(
        manageSinpeAccountSaveInput: {
            user: $user
            idBrand: $idBrand
            identification: $identification
            account_number: $account_number
            id_Currency: $id_Currency
            nameAccount: $nameAccount
            country: $country
            id_account: $id_account
            isFavorite: $isFavorite
            option: $option
            id_Bank: $idBank
            type_Account: $typeAccount
        }
    ) {
        result {
            id_Account_Sinpe
        }
    }
}
