mutation ProcessTransfer365Mobile(
    $identification: String!
    $destinationPhone: String!
    $destinationBankId: String!
    $typeAccountId: String!
    $destinationName: String!
    $destinationLastName: String!
    $amount: Decimal!
    $motive: String!
    $user: String!
    $idBrand: Int!
    $destinationType: String!
) {
    transferMovil365(
        transferMovil365Input: {
            identification: $identification
            destinationPhone: $destinationPhone
            destinationBank: $destinationBankId
            destinationName: $destinationName
            destinationLastName: $destinationLastName
            typeAccount: $typeAccountId
            destinationType: $destinationType
            amountToTransfer: $amount
            reasonForTransfer: $motive
            user: $user
            idBrand: $idBrand
        }
    ) {
        result {
            bankAuthorization {
                authorizationId
                message
            }
            transfer365 {
                message
            }
        }
        status
        message
        detail
    }
}