mutation SaveAutomatedSmartAccount(
    $user: String!,
    $idBrand: Int!,
    $identificationNumber: String!,
    $idRequest: Long!
){
    saveAutomatedSmartAccount(
        saveAutomatedSmartAccountInput: {
            user: $user
            idBrand: $idBrand
            identificationNumber: $identificationNumber
            idRequest: $idRequest
        }
    ) {
        result {
            requestID
            message
            idAccount : iDAccount
            documentRoute
            identification
        }
    }
}
