mutation UpdateACHAccount(
    $accountId: Int!,
    $description: String!,
    $titularName: String!,
    $idBrand: Int!,
    $user: String!,
    $identification: String!
    $accountNumber: String!
) {
    aCHTransferFavoriteUpdate(
        aCHTransferFavoriteUpdateInput: {
            accountForAchTransferId: $accountId
            description: $description
            idBrand: $idBrand
            user: $user
            titularName: $titularName,
            identificacionNumber: $identification
            accountNumber: $accountNumber
        }
    ) {
        result {
            accountForAchTransferId
        }
        status
        message
        detail
    }
}