mutation SaveClientBankAccount(
    $idClient: Long!,
    $id_Banco: Int!,
    $numeroCuenta: String!,
    $id_Moneda: Int!,
    $id_Tipo_Cuenta: Int,
    $idLoanClient: Long!,
    $user: String!,
    $idBrand: Int!
){
  saveClientBankAccount(
    saveClientBankAccountInput: {
      idClient: $idClient
      id_Banco: $id_Banco
      numeroCuenta: $numeroCuenta
      id_Moneda: $id_Moneda
      id_Tipo_Cuenta: $id_Tipo_Cuenta
      idLoanClient: $idLoanClient
      user: $user
      idBrand: $idBrand
    }
  ) {
    isUpdate
    status
    message
    detail
  }
}