query ValidateUserStatus($pkUser: Long!, $identification: String!, $user: String!, $idBrand: Int!){
    validateUserStatus(
        userStatusInput: {
            pkUser: $pkUser
            identification: $identification
            user: $user
            idBrand: $idBrand
        }
    ) {
        infoUser {
            pkUser
            idBrand
            fullName
            firstName
            secondName
            lastName
            secondLastName
            userName
            email
            phone
            birthDate
            idClient
            vISADirect_ID
            vISADirect_Usuario
            statusOnfido
            fecha_ultimo_acceso
        }
        infoCredit {
            idClient
            idLoanClient
            status
            infoPreApprove {
                idUserRequest
                status
                infoProducts {
                    idProduct
                    amountAvailable
                    amountAvailableFormat
                    symbolCurrency
                }
                selectedAmount
                statusFirm
                currentStep
            }
        }
        infoVirtualCard {
            status
        }
        infoBankAccount {
            statusFirm
            status
        }
        infoCrypto {
            status
        }
    }
}