type CreditQuery {
  creditOffer(creditOfferInput: creditOfferInput): creditOffer

  paymentAmount(paymentAmountInput: balanceCreditInput): paymentAmount

  screenConfigText(screenConfigInput: screenConfigInput): [screenConfigText]

  employmentSituation(employmentSituationInput: screenConfigInput): [screenConfigText]

  ocupation(ocupationInput: screenConfigInput): [screenConfigText]

  profession(professionInput: screenConfigInput): [screenConfigText]

  homeProvince(homeProvinceInput: screenConfigInput): [screenConfigText]

  homeCanton(homeCantonInput: screenConfigInput): [screenConfigText]

  homeDistrict(homeDistrictInput: screenConfigInput): [screenConfigText]

  companyProvince(companyProvinceInput: screenConfigInput): [screenConfigText]

  companyCanton(companyCantonInput: screenConfigInput): [screenConfigText]

  companyDistrict(companyDistrictInput: screenConfigInput): [screenConfigText]

  regularExpression(regularExpressionInput: regularExpressionInput): [regularExpression]

  banks(banksInput: screenConfigInput): [screenConfigText]

  getClientBankAccount(getClientBankAccountInput: getClientBankAccountInput): [getClientBankAccount]

  getClientAutomaticDebit(getClientAutomaticDebitInput: getClientAutomaticDebitInput): [getClientAutomaticDebit]

  terminsAndConditions(terminsAndConditionsInput: terminsAndConditionsInput): terminsAndConditions

  listBanks(listBanksInput: listBanksInput): [listBanks]

  creditExtensionAmount(creditExtensionAmountInput: creditExtensionAmountInput): creditExtensionAmount

  creditExtensionMessage(creditExtensionMessageInput: creditExtensionMessageInput): creditExtensionMessage

  getPaymentPoints(paymentPointsInput: paymentPointsInput): [getPaymentPoints]

  getPromissoryNoteDetail(getPromissoryNoteDetailInput: getPromissoryNoteDetailInput): [getPromissoryNoteDetail]

  getExchangeRateCredit(exchangeRateCreditInput: exchangeRateCreditInput): getExchangeRate

  accountStatement(accountStatementInput: accountStatementInputType): accountStatement
}

type creditOffer {
  """
  creditOffer idUserRequest
  """
  idUserRequest: Long

  """
  creditOffer products
  """
  products: [products]

  """
  creditOffer rejectedBlaze
  """
  rejectedBlaze: Boolean!
}

scalar Long

type products {
  """
  products ID_PRODUCTO
  """
  iD_PRODUCTO: String!

  """
  products LIMITE_CREDITO
  """
  lIMITE_CREDITO: String!

  """
  products TRACTO
  """
  tRACTO: String!

  """
  products MINIMO_DESEMBOLSO
  """
  mINIMO_DESEMBOLSO: String!

  """
  products MAXIMO_DESEMBOLSO
  """
  mAXIMO_DESEMBOLSO: String!

  """
  products DESCRIPCION_PROMOCION
  """
  dESCRIPCION_PROMOCION: String!

  """
  products PK_PSE_CAT_PROMOCION_PLAZO
  """
  pK_PSE_CAT_PROMOCION_PLAZO: String!

  """
  products PLAZO
  """
  pLAZO: String!

  """
  products MONEDA
  """
  mONEDA: String!

  """
  products ES_PROMOCIONAL
  """
  eS_PROMOCIONAL: String!

  """
  products CICLO
  """
  cICLO: String!

  """
  products TASA_INTERES_NORMAL
  """
  tASA_INTERES_NORMAL: String!

  """
  products STR_TASA_INTERES_NORMAL
  """
  sTR_TASA_INTERES_NORMAL: String!

  """
  products CUOTA
  """
  cUOTA: String!

  """
  products CUOTA_AUTORIZA
  """
  cUOTA_AUTORIZA: String!

  """
  products COMISION_DESEMBOLSO
  """
  cOMISION_DESEMBOLSO: String!

  """
  products STR_COMISION_DESEMBOLSO
  """
  sTR_COMISION_DESEMBOLSO: String!

  """
  products FECHA_PAGO
  """
  fECHA_PAGO: String!

  """
  products NOMBRE_MONEDA
  """
  nOMBRE_MONEDA: String!

  """
  products STR_MINIMO_DESEMBOLSO
  """
  sTR_MINIMO_DESEMBOLSO: String!

  """
  products STR_MAXIMO_DESEMBOLSO
  """
  sTR_MAXIMO_DESEMBOLSO: String!

  """
  products CUOTA_ORIGINAL
  """
  cUOTA_ORIGINAL: String!

  """
  products Mensaje_Plazo
  """
  mensaje_Plazo: String!

  """
  products Mensaje_Condiciones
  """
  mensaje_Condiciones: String!

  """
  products Nombre_Usuario
  """
  nombre_Usuario: String!

  """
  products Cuota_Real
  """
  cuota_Real: Decimal!

  """
  products PLAZO_NUMERICO
  """
  pLAZO_NUMERICO: Int!

  """
  products BIT_REQUIERE_FORMALIZACION
  """
  bIT_REQUIERE_FORMALIZACION: String
}

scalar Decimal

input creditOfferInput {
  pkUser: Long!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

type paymentAmount {
  """
  paymentAmount paymentAmount
  """
  paymentAmount: Decimal!

  """
  paymentAmount paymentAmountLabel
  """
  paymentAmountLabel: String!
}

input balanceCreditInput {
  amount: Decimal!

  months: String!

  idProduct: String!

  currencySymbol: String!

  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

type screenConfigText {
  """
  screenConfigText Pk_Suv_Cat_Opcion_Pregunta_Solicitud_Credito
  """
  pk_Suv_Cat_Opcion_Pregunta_Solicitud_Credito: Int!

  """
  screenConfigText Fk_Suv_Cat_Pregunta_Solicitud_Credito
  """
  fk_Suv_Cat_Pregunta_Solicitud_Credito: Int!

  """
  screenConfigText Fk_Suv_Cat_Opcion_Pregunta_Solicitud_Credito
  """
  fk_Suv_Cat_Opcion_Pregunta_Solicitud_Credito: Int

  """
  screenConfigText Tipo_Control
  """
  tipo_Control: String!

  """
  screenConfigText Descripcion
  """
  descripcion: String!

  """
  screenConfigText Es_Catalogo_Core
  """
  es_Catalogo_Core: Boolean!

  """
  screenConfigText Pk_Identificador_Catalogo
  """
  pk_Identificador_Catalogo: String

  """
  screenConfigText Es_Catalogo_Sucursal
  """
  es_Catalogo_Sucursal: Boolean!

  """
  screenConfigText Utiliza_Valor
  """
  utiliza_Valor: Boolean!

  """
  screenConfigText Valor_Catalogo
  """
  valor_Catalogo: String

  """
  screenConfigText Llave_Formulario
  """
  llave_Formulario: String!

  """
  screenConfigText Monto_Maximo
  """
  monto_Maximo: String

  """
  screenConfigText SubOpciones
  """
  subOpciones: [screenConfigSubText]

  """
  screenConfigText fk_Identificador_Catalogo
  """
  fk_Identificador_Catalogo: Int!

  """
  screenConfigText grupo
  """
  grupo: String!

  """
  screenConfigText evento
  """
  evento: String!

  """
  screenConfigText Interno
  """
  interno: String

  """
  screenConfigText Valor
  """
  valor: String
}

type screenConfigSubText {
  """
  screenConfigText Tipo_Control
  """
  tipo_Control: String!

  """
  screenConfigText Descripcion
  """
  descripcion: String!

  """
  screenConfigText Pk_Identificador_Catalogo
  """
  pk_Identificador_Catalogo: String

  """
  screenConfigText Utiliza_Valor
  """
  utiliza_Valor: Boolean!

  """
  screenConfigText Valor_Catalogo
  """
  valor_Catalogo: String

  """
  screenConfigText fk_Identificador_Catalogo
  """
  fk_Identificador_Catalogo: Int!

  """
  screenConfigText Interno
  """
  interno: String

  """
  screenConfigText Valor
  """
  valor: String
}

input screenConfigInput {
  pkUser: Int!

  group: String

  keyForm: String

  fkCatalogIdentifier: String

  origin: Boolean

  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String

  idUserRequest: String!
}

type regularExpression {
  """
  regularExpression INT_PK_VEN_CAT_EXPRESION_REGULAR
  """
  iNT_PK_VEN_CAT_EXPRESION_REGULAR: Int!

  """
  regularExpression STR_LLAVE_04
  """
  sTR_LLAVE_04: String!

  """
  regularExpression STR_DESCRIPCION
  """
  sTR_DESCRIPCION: String!

  """
  regularExpression STR_PATRON_EXPRESION
  """
  sTR_PATRON_EXPRESION: String!

  """
  regularExpression INT_FK_LLAVE_FORANEA
  """
  iNT_FK_LLAVE_FORANEA: Int!

  """
  regularExpression INT_ID_TIPO_CUENTA_DESEMBOLSO
  """
  iNT_ID_TIPO_CUENTA_DESEMBOLSO: Int!
}

input regularExpressionInput {
  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

type getClientBankAccount {
  """
  getClientAutomaticDebit Origen
  """
  origen: String!

  """
  getClientAutomaticDebit Id
  """
  id: Long!

  """
  getClientAutomaticDebit Id_Banco
  """
  id_Banco: Int!

  """
  getClientAutomaticDebit descripcion_banco
  """
  descripcion_banco: String!

  """
  getClientAutomaticDebit NumeroCuenta
  """
  numeroCuenta: String!

  """
  getClientAutomaticDebit FechaDebito
  """
  fechaDebito: String

  """
  getClientAutomaticDebit Id_Cliente
  """
  id_Cliente: Long!

  """
  getClientAutomaticDebit Id_Moneda
  """
  id_Moneda: Int!

  """
  getClientAutomaticDebit Usuario
  """
  usuario: String

  """
  getClientAutomaticDebit Id_Prestamo
  """
  id_Prestamo: Int!

  """
  getClientAutomaticDebit Id_Moneda_Destino
  """
  id_Moneda_Destino: Int!
}

input getClientBankAccountInput {
  user: String!

  idBrand: Int!

  tenantId: String

  traceidentifier: String

  id_Cliente: Int!

  id_Prestamo: Int!
}

type getClientAutomaticDebit {
  """
  getClientAutomaticDebit Origen
  """
  origen: String!

  """
  getClientAutomaticDebit Id
  """
  id: Long!

  """
  getClientAutomaticDebit Id_Banco
  """
  id_Banco: Int!

  """
  getClientAutomaticDebit descripcion_banco
  """
  descripcion_banco: String!

  """
  getClientAutomaticDebit NumeroCuenta
  """
  numeroCuenta: String!

  """
  getClientAutomaticDebit FechaDebito
  """
  fechaDebito: String!

  """
  getClientAutomaticDebit Id_Cliente
  """
  id_Cliente: Long!

  """
  getClientAutomaticDebit Id_Moneda
  """
  id_Moneda: Int!

  """
  getClientAutomaticDebit Usuario
  """
  usuario: String!

  """
  getClientAutomaticDebit Id_Prestamo
  """
  id_Prestamo: Int!

  """
  getClientAutomaticDebit Id_Moneda_Destino
  """
  id_Moneda_Destino: Int!
}

input getClientAutomaticDebitInput {
  user: String!

  idBrand: Int!

  tenantId: String

  traceidentifier: String

  id_Cliente: Int!

  id_Prestamo: Int!

  proceso: String!
}

type terminsAndConditions {
  """
  terminsAndConditions terminsAndConditionsHtml
  """
  terminsAndConditionsHtml: String!
}

input terminsAndConditionsInput {
  user: String!

  idBrand: Int!

  tenantId: String

  traceidentifier: String

  styleDark: Boolean!
}

type listBanks {
  """
  listBanks id
  """
  id: Long

  """
  listBanks banco
  """
  banco: String

  """
  listBanks bit_SINPE
  """
  bit_SINPE: Short

  """
  listBanks p_Int_Sub_Origen
  """
  p_Int_Sub_Origen: Short

  """
  listBanks bit_Interno
  """
  bit_Interno: Short

  """
  listBanks tin_Length_SINPE
  """
  tin_Length_SINPE: Short

  """
  listBanks str_Mask_Interno
  """
  str_Mask_Interno: String

  """
  listBanks bit_Estado
  """
  bit_Estado: Boolean

  """
  listBanks fk_Suv_Mtr_Usuario
  """
  fk_Suv_Mtr_Usuario: Int

  """
  listBanks fk_Suv_Cat_Marca
  """
  fk_Suv_Cat_Marca: Short

  """
  listBanks subOrigen
  """
  subOrigen: Short

  """
  listBanks cODIGO_ACH
  """
  cODIGO_ACH: String
}

scalar Short

input listBanksInput {
  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

type creditExtensionAmount {
  """
  creditExtensionAmount amountMax
  """
  amountMax: Decimal

  """
  creditExtensionAmount amountMin
  """
  amountMin: Decimal

  """
  creditExtensionAmount labelAmountMaxAvailable
  """
  labelAmountMaxAvailable: String

  """
  creditExtensionAmount labelAmountMinAvailable
  """
  labelAmountMinAvailable: String

  """
  creditExtensionAmount symbol
  """
  symbol: String

  """
  creditExtensionAmount amountTract
  """
  amountTract: Int

  """
  creditExtensionAmount idLoanClient
  """
  idLoanClient: Long

  """
  creditExtensionAmount idProductBase
  """
  idProductBase: Int

  """
  creditExtensionAmount cicle
  """
  cicle: Int

  """
  creditExtensionAmount quotaMax
  """
  quotaMax: Decimal

  """
  creditExtensionAmount promissoryNote
  """
  promissoryNote: String

  """
  creditExtensionAmount amountMinDisbursementCK
  """
  amountMinDisbursementCK: Decimal

  """
  creditExtensionAmount paramMore
  """
  paramMore: Boolean
}

input creditExtensionAmountInput {
  idClient: Int!

  currency: String!

  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

type creditExtensionMessage {
  """
  creditExtensionMessage pkPromotion
  """
  pkPromotion: Long

  """
  creditExtensionMessage pkPromotionMonth
  """
  pkPromotionMonth: Int

  """
  creditExtensionMessage idClient
  """
  idClient: Long

  """
  creditExtensionMessage amountRequest
  """
  amountRequest: Decimal

  """
  creditExtensionMessage tableClass
  """
  tableClass: String

  """
  creditExtensionMessage idProductSelect
  """
  idProductSelect: Int

  """
  creditExtensionMessage idProductBase
  """
  idProductBase: Int

  """
  creditExtenscreditExtensionMessageion monthSelect
  """
  monthSelect: Int

  """
  creditExtensionMessage quotaCalculator
  """
  quotaCalculator: String

  """
  creditExtensionMessage requiredSms
  """
  requiredSms: Boolean

  """
  creditExtensionMessage numberTelephone
  """
  numberTelephone: String

  """
  creditExtensionMessage fkUser
  """
  fkUser: Int

  """
  creditExtensionMessage menssageAmountExtensionPart1
  """
  menssageAmountExtensionPart1: String

  """
  creditExtensionMessage menssageAmountExtensionPart2
  """
  menssageAmountExtensionPart2: String

  """
  creditExtensionMessage menssageInformationExtensionPart1
  """
  menssageInformationExtensionPart1: String

  """
  creditExtensionMessage menssageInformationExtensionPart2
  """
  menssageInformationExtensionPart2: String

  """
  creditExtensionMessage menssageInformationApp
  """
  menssageInformationApp: String

  """
  creditExtensionMessage currency
  """
  currency: String

  """
  creditExtensionMessage promissoryNote
  """
  promissoryNote: String

  """
  creditExtension product
  """
  product: [creditExtensionProductList]
}

type creditExtensionProductList {
  """
  creditExtensionProductList pkPromotion
  """
  pkPromotion: Long

  """
  creditExtensionProductList pkPromotionMonth
  """
  pkPromotionMonth: Int

  """
  creditExtensionProductList DescriptionPromotionTerm
  """
  descriptionPromotionTerm: String

  """
  creditExtensionProductList rateInterestNormal
  """
  rateInterestNormal: String

  """
  creditExtensionProductList rateIntMoratorium
  """
  rateIntMoratorium: String

  """
  creditExtensionProductList comissionMoratorium
  """
  comissionMoratorium: Decimal

  """
  creditExtensionProductList comissionDisbursement
  """
  comissionDisbursement: String

  """
  creditExtensionProductList strRateInterestNormal
  """
  strRateInterestNormal: String

  """
  creditExtensionProductList strComissionDisbursement
  """
  strComissionDisbursement: String

  """
  creditExtensionProductList extensionCommission
  """
  extensionCommission: Decimal

  """
  creditExtensionProductList interestRateExpansion
  """
  interestRateExpansion: String

  """
  creditExtensionProductList showDetail
  """
  showDetail: String

  """
  creditExtensionProductList month
  """
  month: String

  """
  creditExtensionProductList quota
  """
  quota: Decimal

  """
  creditExtensionProductList quotaTotal
  """
  quotaTotal: Decimal

  """
  creditExtensionProductList cicle
  """
  cicle: Int

  """
  creditExtensionProductList isPromotion
  """
  isPromotion: Boolean

  """
  creditExtensionProductList datePay
  """
  datePay: DateTime

  """
  creditExtensionProductList datePayActuality
  """
  datePayActuality: DateTime

  """
  creditExtensionProductList strQuota
  """
  strQuota: String

  """
  creditExtensionProductList strQuotaTotal
  """
  strQuotaTotal: String

  """
  creditExtensionProductList quotaActuality
  """
  quotaActuality: Decimal

  """
  creditExtensionProductList strQuotaActuality
  """
  strQuotaActuality: String

  """
  creditExtensionProductList strDatePay
  """
  strDatePay: String

  """
  creditExtensionProductList strDatePayActuality
  """
  strDatePayActuality: String
}

"""
The `DateTime` scalar type represents a date and time. `DateTime` expects timestamps to be formatted in accordance with the [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) standard.
"""
scalar DateTime

input creditExtensionMessageInput {
  idClient: Int!

  currency: String!

  user: String!

  idBrand: Int!

  amountRequest: Decimal!

  tenantId: String

  traceIdentifier: String

  modelCreditExtensionConfigurator: modelCreditExtensionConfiguratorInput!
}

input modelCreditExtensionConfiguratorInput {
  quotaMax: Decimal!

  idLoanClient: Int!

  idProductBase: Int!

  cicle: Int!
}

type getPaymentPoints {
  """
  getPaymentPoints idBrand
  """
  idBrand: Short

  """
  getPaymentPoints name
  """
  name: String

  """
  getPaymentPoints description
  """
  description: String

  """
  getPaymentPoints address map
  """
  address: String

  """
  getPaymentPoints address description
  """
  addressDescription: String

  """
  getPaymentPoints schedule
  """
  schedule: String
}

input paymentPointsInput {
  idBrand: Int!

  user: String

  name: String

  tenantId: String

  traceIdentifier: String
}

type getPromissoryNoteDetail {
  """
  getPromissoryNoteDetail Title
  """
  title: String

  """
  getPromissoryNoteDetail Values_Transactions
  """
  values_Transactions: [getPromissoryNoteDetailValues]
}

type getPromissoryNoteDetailValues {
  """
  getPromissoryNoteDetailValues Fk_Suv_Cat_Marca
  """
  tipo: String!

  """
  getPromissoryNoteDetailValues Fecha_Aplicacion
  """
  fecha_Aplicacion: DateTime!

  """
  getPromissoryNoteDetailValues Monto
  """
  monto: String!

  """
  getPromissoryNoteDetailValues Id_Prestamo
  """
  id_Prestamo: Long!

  """
  getPromissoryNoteDetailValues Fecha_Inicio
  """
  fecha_Inicio: DateTime!

  """
  getPromissoryNoteDetailValues Fecha_Fin
  """
  fecha_Fin: DateTime!

  """
  getPromissoryNoteDetailValues Fecha_Aplicacion_Label
  """
  fecha_Aplicacion_Label: String

  """
  getPromissoryNoteDetailValues Monto_Label
  """
  monto_Label: String

  """
  getPromissoryNoteDetailValues Client_Secret
  """
  client_Secret: String

  """
  getPromissoryNoteDetailValues Moneda
  """
  moneda: String!

  """
  getPromissoryNoteDetailValues Mes
  """
  mes: String

  """
  getPromissoryNoteDetailValues Indicador
  """
  indicador: Int!

  """
  getPromissoryNoteDetailValues Tipo_Transaccion
  """
  tipo_Transaccion: String!

  """
  getPromissoryNoteDetailValues Id_Tipo_Transaccion
  """
  id_Tipo_Transaccion: Int!
}

input getPromissoryNoteDetailInput {
  id_Prestamo: Int!

  opcion: String!

  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

type getExchangeRate {
  """
  getExchangeRate result
  """
  result: exchangeRateResult

  """
  getExchangeRate Status
  """
  status: Int

  """
  getExchangeRate Message
  """
  message: String
}

type exchangeRateResult {
  """
  exchangeRateResult exchangeRate
  """
  exchangeRate: Float!

  """
  exchangeRateResult amount
  """
  amount: Decimal!

  """
  exchangeRateResult convertedAmount
  """
  convertedAmount: Decimal!
}

input exchangeRateCreditInput {
  user: String!

  idBrand: Int!

  tenantId: String

  traceidentifier: String

  identification: String

  idOriginCurrency: String

  idDestinationCurrency: String

  identificacionNumber: String

  amount: Decimal
}

type accountStatement {
  """
  accountStatement bytePDF
  """
  bytePDF: [Byte!]!
}

scalar Byte

input accountStatementInputType {
  pagare: String!

  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

type CreditMutation {
  saveCreditFlowStep(saveCreditFlowStepInput: saveCreditFlowStepInput): saveCreditFlowStep

  saveCreditApplication(creditApplicationInputType: CreditApplicationInputType): saveCreditApplication

  saveCreditOperation(saveCreditOperationInput: saveCreditOperationInput): saveCreditOperation

  saveCreditOffer(saveCreditOfferInput: saveCreditOfferInput): creditOffer

  proccessPaymentList(proccessPaymentListInput: proccessPaymentListInput): proccessPaymentList

  saveTermsAndConditions(saveTermsAndConditionsInput: saveTermsAndConditionsInput): saveTermsAndConditions

  activatedClientAutomaticDebit(clientAutomaticDebitInput: clientAutomaticDebitInput): clientAutomaticDebit

  deactivatedClientAutomaticDebit(clientAutomaticDebitInput: clientAutomaticDebitInput): clientAutomaticDebit

  saveClientBankAccount(saveClientBankAccountInput: saveClientBankAccountInput): clientAutomaticDebit

  saveCreditExtensionDetail(creditExtensionDetailInput: creditExtensionDetailInput): creditExtensionDetail

  processCreditExtensionDetail(processCreditExtensionDetailInput: processCreditExtensionDetailInput): creditExtensionDetail
}

type saveCreditFlowStep {
  """
  saveCreditFlowStep MessageInfo
  """
  messageInfo: String!

  """
  saveCreditFlowStep Status
  """
  status: Int!

  """
  saveCreditFlowStep Result
  """
  result: String!
}

input saveCreditFlowStepInput {
  user: String!

  idBrand: Int!

  tenantId: String

  traceidentifier: String

  infoQuestion: [questionsDataListInput]!

  idLogUserRequest: Int!

  idUser: Int!

  currentStep: String!
}

input questionsDataListInput {
  idQuestionRequestCredit: Int!

  idOptionQuestionRequestCredit: Int

  createUser: String

  updateUser: String

  createDate: Date

  updateDate: Date

  identificator: String

  value: String

  active: Boolean

  controlType: String

  isCoreCatalogue: Boolean

  isBranchOfficeCatalogue: Boolean

  useValue: Boolean

  maximumAmount: String

  description: String

  valueCatalogue: String

  idIdentificatorCatalogue: String
}

"""
The `Date` scalar type represents a year, month and day in accordance with the [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) standard.
"""
scalar Date

type saveCreditApplication {
  """
  saveCreditApplication Pk_Suv_Log_Solicitud_Usuario
  """
  pk_Suv_Log_Solicitud_Usuario: Int!

  """
  saveCreditApplication Fk_Suv_Mtr_Usuario
  """
  fk_Suv_Mtr_Usuario: Int!

  """
  saveCreditApplication Usuario_Modificacion
  """
  usuario_Modificacion: String!

  """
  saveCreditApplication Fecha_Modificacion
  """
  fecha_Modificacion: DateTime!

  """
  saveCreditApplication Moneda_Prestamo
  """
  moneda_Prestamo: String!

  """
  saveCreditApplication Moneda_Escenario
  """
  moneda_Escenario: String!

  """
  saveCreditApplication Monto_Solicitado
  """
  monto_Solicitado: Decimal!

  """
  saveCreditApplication Pk_Pse_Cat_Promocion
  """
  pk_Pse_Cat_Promocion: Int!

  """
  saveCreditApplication Id_Producto
  """
  id_Producto: Int!

  """
  saveCreditApplication Plazo
  """
  plazo: String!

  """
  saveCreditApplication Descripcion_Promocion_Plazo
  """
  descripcion_Promocion_Plazo: String!

  """
  saveCreditApplication Tasa
  """
  tasa: String!

  """
  saveCreditApplication Cuota_Total
  """
  cuota_Total: String!

  """
  saveCreditApplication Comision_Desembolso
  """
  comision_Desembolso: String!

  """
  saveCreditApplication Tracto
  """
  tracto: Decimal!

  """
  saveCreditApplication Monto_Disponible
  """
  monto_Disponible: Decimal!

  """
  saveCreditApplication Monto_Minimo_Credito
  """
  monto_Minimo_Credito: Decimal!

  """
  saveCreditApplication Fecha_Pago
  """
  fecha_Pago: String!

  """
  saveCreditApplication currentStep
  """
  currentStep: String!

  """
  saveCreditApplication Status
  """
  status: Int

  """
  saveCreditApplication Message
  """
  message: String

  """
  saveCreditApplication Detail
  """
  detail: String
}

input CreditApplicationInputType {
  idUserRequest: Int!

  pkUser: Int!

  descPromotion: String!

  interestRate: String!

  symbolCurrency: String!

  descCurrency: String!

  selectedAmount: Decimal!

  idProduct: Int!

  idPromotion: Int!

  months: String!

  commisionPercentage: String!

  tractAmount: Decimal!

  minimunAmount: Decimal!

  paymentDate: String!

  paymentAmount: String!

  creditLimit: Decimal!

  currentStep: String!

  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

type saveCreditOperation {
  """
  saveCreditOperation idPrint
  """
  idPrint: Long

  """
  saveCreditOperation showFinalScreen
  """
  showFinalScreen: Boolean!

  """
  saveCreditOperation showOutSchedule
  """
  showOutSchedule: Boolean!
}

input saveCreditOperationInput {
  idUserRequest: Int!

  pkUser: Int!

  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

input saveCreditOfferInput {
  pkUser: Long!

  idUserRequest: Long!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

type proccessPaymentList {
  """
  proccessPaymentList numero_Referencia_Interno
  """
  cODIGO_RECHAZO_SINPE: String!

  """
  proccessPaymentList numero_Referencia_Interno
  """
  mOTIVO_RECHAZO_SINPE: String!

  """
  proccessPaymentList numero_Referencia_Interno
  """
  mENSAJE_RESPUESTA: String!

  """
  proccessPaymentList numero_Referencia_Interno
  """
  mENSAJE_RESPUESTA_INTERNO: String!

  """
  proccessPaymentList numero_Referencia_Interno
  """
  nUMERO_REFERENCIA_INTERNO: String!

  """
  proccessPaymentList numero_Referencia_Interno
  """
  nUM_REF_SINPE: String!

  """
  proccessPaymentList Status
  """
  status: Int

  """
  proccessPaymentList Message
  """
  message: String

  """
  proccessPaymentList Detail
  """
  detail: String
}

input proccessPaymentListInput {
  user: String!

  idBrand: Int!

  tenantId: String

  traceidentifier: String

  id_Cliente: Int!

  identificacion: String!

  numeroCuentaOrigen: String!

  numeroCuentaDestino: String!

  id_Moneda: String!

  monto: Decimal!

  nombreCliente: String!

  descripcion: String!

  cuentaDestino: [CuentaDestino]!
}

input CuentaDestino {
  numeroCuentaDestino: String!

  idMonedaDestino: String!

  montoDestino: Decimal!
}

type saveTermsAndConditions {
  """
  saveTermsAndConditions status
  """
  status: Int

  """
  saveTermsAndConditions message
  """
  message: String

  """
  saveTermsAndConditions detail
  """
  detail: String
}

input saveTermsAndConditionsInput {
  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String

  pkUser: Int!

  currentFlow: String!

  identification: String!

  styleDark: Boolean
}

type clientAutomaticDebit {
  """
  clientAutomaticDebit IsUpdate
  """
  isUpdate: Boolean!

  """
  clientAutomaticDebit status
  """
  status: Int

  """
  clientAutomaticDebit message
  """
  message: String

  """
  clientAutomaticDebit detail
  """
  detail: String
}

input clientAutomaticDebitInput {
  user: String!

  idBrand: Int!

  tenantId: String

  traceidentifier: String

  id_Cliente: Int!

  id_Prestamo: Int!

  origen: String!

  id: Int!

  id_Moneda_Destino: Int

  id_Banco: Int

  numeroCuenta: String

  id_Moneda: Int
}

input saveClientBankAccountInput {
  id_Cliente: Int!

  id_Banco: Int!

  numeroCuenta: String!

  id_Moneda: Int!

  id_Prestamo: Int!

  user: String!

  idBrand: Int!

  tenantId: String

  traceidentifier: String
}

type creditExtensionDetail {
  """
  creditExtensionDetail Fk_Suv_Mtr_Control_Flujo
  """
  fk_Suv_Mtr_Control_Flujo: Long

  """
  creditExtensionDetail PK_PSE_CAT_PROMOCION
  """
  pK_PSE_CAT_PROMOCION: Long

  """
  creditExtensionDetail PK_PSE_CAT_PROMOCION_PLAZO
  """
  pK_PSE_CAT_PROMOCION_PLAZO: Int

  """
  creditExtensionDetail Fk_Suv_Cat_Marca
  """
  fk_Suv_Cat_Marca: Short

  """
  creditExtensionDetail Id_Como_Te_Enteraste
  """
  id_Como_Te_Enteraste: Short

  """
  creditExtensionDetail Como_Te_Enteraste
  """
  como_Te_Enteraste: String

  """
  creditExtensionDetail Id_Proposito
  """
  id_Proposito: Short

  """
  creditExtensionDetail Proposito
  """
  proposito: String

  """
  creditExtensionDetail Monto_Inicial
  """
  monto_Inicial: String

  """
  creditExtensionDetail Monto_Seleccionado
  """
  monto_Seleccionado: String

  """
  creditExtensionDetail Id_Producto
  """
  id_Producto: Short

  """
  creditExtensionDetail Descripcion_Producto
  """
  descripcion_Producto: String

  """
  creditExtensionDetail Plazo
  """
  plazo: String

  """
  creditExtensionDetail Tasa
  """
  tasa: String

  """
  creditExtensionDetail Cuota
  """
  cuota: String

  """
  creditExtensionDetail Cuota_Total
  """
  cuota_Total: String

  """
  creditExtensionDetail Comision_Desembolso
  """
  comision_Desembolso: String

  """
  creditExtensionDetail Cuota_Maxima
  """
  cuota_Maxima: String

  """
  creditExtensionDetail Ciclo
  """
  ciclo: Int

  """
  creditExtensionDetail Pagare
  """
  pagare: String

  """
  creditExtensionDetail Proximo_Pago
  """
  proximo_Pago: DateTime

  """
  creditExtensionDetail Id_Forma_Desembolso
  """
  id_Forma_Desembolso: Short

  """
  creditExtensionDetail Forma_Desembolso
  """
  forma_Desembolso: String

  """
  creditExtensionDetail Id_Forma_Entrega
  """
  id_Forma_Entrega: Short

  """
  creditExtensionDetail Forma_Entrega
  """
  forma_Entrega: String

  """
  creditExtensionDetail Id_Agencia
  """
  id_Agencia: Short

  """
  creditExtensionDetail Agente
  """
  agente: String

  """
  creditExtensionDetail Fecha_Entrega
  """
  fecha_Entrega: DateTime

  """
  creditExtensionDetail Id_Horario_Entrega
  """
  id_Horario_Entrega: Short

  """
  creditExtensionDetail Horario_Entrega
  """
  horario_Entrega: String

  """
  creditExtensionDetail Horario_Entrega_Desde
  """
  horario_Entrega_Desde: String

  """
  creditExtensionDetail Horario_Entrega_Hasta
  """
  horario_Entrega_Hasta: String

  """
  creditExtensionDetail Id_Hora_Entrega
  """
  id_Hora_Entrega: Short

  """
  creditExtensionDetail Hora_Entrega
  """
  hora_Entrega: String

  """
  creditExtensionDetail Id_Cliente
  """
  id_Cliente: Long

  """
  creditExtensionDetail Id_Tipo_Direccion
  """
  id_Tipo_Direccion: Short

  """
  creditExtensionDetail Tipo_SAP
  """
  tipo_SAP: String

  """
  creditExtensionDetail Provincia
  """
  provincia: String

  """
  creditExtensionDetail Canton
  """
  canton: String

  """
  creditExtensionDetail Distrito
  """
  distrito: String

  """
  creditExtensionDetail LugarEntrega
  """
  lugarEntrega: String

  """
  creditExtensionDetail Detalle_Direccion
  """
  detalle_Direccion: String

  """
  creditExtensionDetail Id_Tipo_Transferencia
  """
  id_Tipo_Transferencia: Int

  """
  creditExtensionDetail Tipo_Transferencia
  """
  tipo_Transferencia: String

  """
  creditExtensionDetail Tipo_Cuenta
  """
  tipo_Cuenta: String

  """
  creditExtensionDetail Id_Numero_Cuenta
  """
  id_Numero_Cuenta: Long

  """
  creditExtensionDetail Numero_Cuenta
  """
  numero_Cuenta: String

  """
  creditExtensionDetail Banco
  """
  banco: String

  """
  creditExtensionDetail Telefono
  """
  telefono: String

  """
  creditExtensionDetail Es_Etapa_Final
  """
  es_Etapa_Final: Boolean

  """
  creditExtensionDetail Enviar_Sms
  """
  enviar_Sms: Boolean

  """
  creditExtensionDetail Id_Ampliacion_Core
  """
  id_Ampliacion_Core: String

  """
  creditExtensionDetail Numero_Gestion
  """
  numero_Gestion: String

  """
  creditExtensionDetail Correo_Electronico
  """
  correo_Electronico: String

  """
  creditExtensionDetail Identificacion_Usuario
  """
  identificacion_Usuario: String

  """
  creditExtensionDetail Usuario_Creacion
  """
  usuario_Creacion: String

  """
  creditExtensionDetail Direccion_IP
  """
  direccion_IP: String

  """
  creditExtensionDetail Es_App
  """
  es_App: Boolean

  """
  creditExtensionDetail Origen
  """
  origen: Boolean

  """
  creditExtensionDetail Tipo_Cambio
  """
  tipo_Cambio: Decimal

  """
  creditExtensionDetail Moneda_Pagare
  """
  moneda_Pagare: String

  """
  creditExtensionDetail Moneda_Desembolso
  """
  moneda_Desembolso: String

  """
  creditExtensionDetail Monto_Real
  """
  monto_Real: Decimal

  """
  creditExtensionDetail Moneda
  """
  moneda: String

  """
  creditExtensionDetail Fk_Suv_Mtr_Usuario
  """
  fk_Suv_Mtr_Usuario: Int

  """
  creditExtensionDetail Pantalla_Confirmacion
  """
  pantalla_Confirmacion: Boolean

  """
  creditExtensionDetail Id_Prestamo
  """
  id_Prestamo: Int

  """
  creditExtensionDetail Status
  """
  status: Int

  """
  creditExtensionDetail Message
  """
  message: String

  """
  creditExtensionDetail Detail
  """
  detail: String
}

input creditExtensionDetailInput {
  accountNumber: String!

  amount: Decimal!

  term: Int!

  idTerm: Int!

  nextPaymentDate: DateTime!

  monthlyPayment: Decimal!

  totalMonthlyPayment: Decimal!

  loanCharge: Decimal!

  interestRateLoan: Decimal!

  regularInterestRate: Decimal!

  cycle: Int!

  idProduct: Int!

  productDescription: String!

  idPromotion: Int!

  userEmail: String!

  pkUser: Int!

  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

input processCreditExtensionDetailInput {
  idFlowControl: Long!

  accountNumber: String!

  currency: String!

  idBankAccount: Long!

  bankAccount: String!

  idLoanForm: Int!

  phoneNumber: String!

  userEmail: String!

  loanForm: String!

  idCredit: Int!

  pkUser: Int!

  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

schema {
  query: CreditQuery
  mutation: CreditMutation
}
