type CreditQuery {
  creditOffer(creditOfferInput: creditOfferInput): creditOffer

  paymentAmount(paymentAmountInput: balanceCreditInput): paymentAmount

  screenConfigText(screenConfigInput: screenConfigInput): [screenConfigText]

  employmentSituation(employmentSituationInput: screenConfigInput): [screenConfigText]

  ocupation(ocupationInput: screenConfigInput): [screenConfigText]

  homeProvince(homeProvinceInput: screenConfigInput): [screenConfigText]

  homeCanton(homeCantonInput: screenConfigInput): [screenConfigText]

  homeDistrict(homeDistrictInput: screenConfigInput): [screenConfigText]

  companyProvince(companyProvinceInput: screenConfigInput): [screenConfigText]

  companyCanton(companyCantonInput: screenConfigInput): [screenConfigText]

  companyDistrict(companyDistrictInput: screenConfigInput): [screenConfigText]

  regularExpression(regularExpressionInput: regularExpressionInput): [regularExpression]

  banks(banksInput: screenConfigInput): [screenConfigText]

  getClientBankAccount(getClientBankAccountInput: getClientBankAccountInput): [getClientBankAccount]

  getClientAutomaticDebit(getClientAutomaticDebitInput: getClientAutomaticDebitInput): [getClientAutomaticDebit]

  terminsAndConditions(terminsAndConditionsInput: terminsAndConditionsInput): terminsAndConditions

  listBanks(listBanksInput: listBanksInput): [listBanks]
}

type creditOffer {
  """
  creditOffer idUserRequest
  """
  idUserRequest: Long

  """
  creditOffer products
  """
  products: [products]
}

scalar Long

type products {
  """
  products ID_PRODUCTO
  """
  iD_PRODUCTO: String!

  """
  products LIMITE_CREDITO
  """
  lIMITE_CREDITO: String!

  """
  products TRACTO
  """
  tRACTO: String!

  """
  products MINIMO_DESEMBOLSO
  """
  mINIMO_DESEMBOLSO: String!

  """
  products MAXIMO_DESEMBOLSO
  """
  mAXIMO_DESEMBOLSO: String!

  """
  products DESCRIPCION_PROMOCION
  """
  dESCRIPCION_PROMOCION: String!

  """
  products PK_PSE_CAT_PROMOCION_PLAZO
  """
  pK_PSE_CAT_PROMOCION_PLAZO: String!

  """
  products PLAZO
  """
  pLAZO: String!

  """
  products MONEDA
  """
  mONEDA: String!

  """
  products ES_PROMOCIONAL
  """
  eS_PROMOCIONAL: String!

  """
  products CICLO
  """
  cICLO: String!

  """
  products TASA_INTERES_NORMAL
  """
  tASA_INTERES_NORMAL: String!

  """
  products STR_TASA_INTERES_NORMAL
  """
  sTR_TASA_INTERES_NORMAL: String!

  """
  products CUOTA
  """
  cUOTA: String!

  """
  products CUOTA_AUTORIZA
  """
  cUOTA_AUTORIZA: String!

  """
  products COMISION_DESEMBOLSO
  """
  cOMISION_DESEMBOLSO: String!

  """
  products STR_COMISION_DESEMBOLSO
  """
  sTR_COMISION_DESEMBOLSO: String!

  """
  products FECHA_PAGO
  """
  fECHA_PAGO: String!

  """
  products NOMBRE_MONEDA
  """
  nOMBRE_MONEDA: String!

  """
  products STR_MINIMO_DESEMBOLSO
  """
  sTR_MINIMO_DESEMBOLSO: String!

  """
  products STR_MAXIMO_DESEMBOLSO
  """
  sTR_MAXIMO_DESEMBOLSO: String!

  """
  products CUOTA_ORIGINAL
  """
  cUOTA_ORIGINAL: String!

  """
  products Mensaje_Plazo
  """
  mensaje_Plazo: String!

  """
  products Mensaje_Condiciones
  """
  mensaje_Condiciones: String!

  """
  products Nombre_Usuario
  """
  nombre_Usuario: String!

  """
  products Cuota_Real
  """
  cuota_Real: Decimal!

  """
  products PLAZO_NUMERICO
  """
  pLAZO_NUMERICO: Int!

  """
  products BIT_REQUIERE_FORMALIZACION
  """
  bIT_REQUIERE_FORMALIZACION: String
}

scalar Decimal

input creditOfferInput {
  pkUser: Int!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

type paymentAmount {
  """
  paymentAmount paymentAmount
  """
  paymentAmount: Decimal!

  """
  paymentAmount paymentAmountLabel
  """
  paymentAmountLabel: String!
}

input balanceCreditInput {
  amount: Decimal!

  months: String!

  idProduct: String!

  currencySymbol: String!

  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

type screenConfigText {
  """
  screenConfigText Pk_Suv_Cat_Opcion_Pregunta_Solicitud_Credito
  """
  pk_Suv_Cat_Opcion_Pregunta_Solicitud_Credito: Int!

  """
  screenConfigText Fk_Suv_Cat_Pregunta_Solicitud_Credito
  """
  fk_Suv_Cat_Pregunta_Solicitud_Credito: Int!

  """
  screenConfigText Fk_Suv_Cat_Opcion_Pregunta_Solicitud_Credito
  """
  fk_Suv_Cat_Opcion_Pregunta_Solicitud_Credito: Int

  """
  screenConfigText Tipo_Control
  """
  tipo_Control: String!

  """
  screenConfigText Descripcion
  """
  descripcion: String!

  """
  screenConfigText Es_Catalogo_Core
  """
  es_Catalogo_Core: Boolean!

  """
  screenConfigText Pk_Identificador_Catalogo
  """
  pk_Identificador_Catalogo: String

  """
  screenConfigText Es_Catalogo_Sucursal
  """
  es_Catalogo_Sucursal: Boolean!

  """
  screenConfigText Utiliza_Valor
  """
  utiliza_Valor: Boolean!

  """
  screenConfigText Valor_Catalogo
  """
  valor_Catalogo: String

  """
  screenConfigText Llave_Formulario
  """
  llave_Formulario: String!

  """
  screenConfigText Monto_Maximo
  """
  monto_Maximo: String

  """
  screenConfigText SubOpciones
  """
  subOpciones: [screenConfigSubText]

  """
  screenConfigText fk_Identificador_Catalogo
  """
  fk_Identificador_Catalogo: Int!

  """
  screenConfigText grupo
  """
  grupo: String!

  """
  screenConfigText evento
  """
  evento: String!

  """
  screenConfigText Interno
  """
  interno: String

  """
  screenConfigText Valor
  """
  valor: String
}

type screenConfigSubText {
  """
  screenConfigText Pk_Suv_Cat_Opcion_Pregunta_Solicitud_Credito
  """
  pk_Suv_Cat_Opcion_Pregunta_Solicitud_Credito: Int!

  """
  screenConfigText Tipo_Control
  """
  tipo_Control: String!

  """
  screenConfigText Descripcion
  """
  descripcion: String!

  """
  screenConfigText Pk_Identificador_Catalogo
  """
  pk_Identificador_Catalogo: String

  """
  screenConfigText Utiliza_Valor
  """
  utiliza_Valor: Boolean!

  """
  screenConfigText Valor_Catalogo
  """
  valor_Catalogo: String

  """
  screenConfigText fk_Identificador_Catalogo
  """
  fk_Identificador_Catalogo: Int!

  """
  screenConfigText Interno
  """
  interno: String

  """
  screenConfigText Valor
  """
  valor: String
}

input screenConfigInput {
  pkUser: Int!

  group: String

  keyForm: String

  fkCatalogIdentifier: String

  origin: Boolean

  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String

  idUserRequest: String
}

type regularExpression {
  """
  regularExpression INT_PK_VEN_CAT_EXPRESION_REGULAR
  """
  iNT_PK_VEN_CAT_EXPRESION_REGULAR: Int!

  """
  regularExpression STR_LLAVE_04
  """
  sTR_LLAVE_04: String!

  """
  regularExpression STR_DESCRIPCION
  """
  sTR_DESCRIPCION: String!

  """
  regularExpression STR_PATRON_EXPRESION
  """
  sTR_PATRON_EXPRESION: String!

  """
  regularExpression INT_FK_LLAVE_FORANEA
  """
  iNT_FK_LLAVE_FORANEA: Int!

  """
  regularExpression INT_ID_TIPO_CUENTA_DESEMBOLSO
  """
  iNT_ID_TIPO_CUENTA_DESEMBOLSO: Int!
}

input regularExpressionInput {
  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

type getClientBankAccount {
  """
  getClientAutomaticDebit Origen
  """
  origen: String!

  """
  getClientAutomaticDebit Id
  """
  id: Long!

  """
  getClientAutomaticDebit Id_Banco
  """
  id_Banco: Int!

  """
  getClientAutomaticDebit descripcion_banco
  """
  descripcion_banco: String!

  """
  getClientAutomaticDebit NumeroCuenta
  """
  numeroCuenta: String!

  """
  getClientAutomaticDebit FechaDebito
  """
  fechaDebito: String

  """
  getClientAutomaticDebit Id_Cliente
  """
  id_Cliente: Long!

  """
  getClientAutomaticDebit Id_Moneda
  """
  id_Moneda: Int!

  """
  getClientAutomaticDebit Usuario
  """
  usuario: String

  """
  getClientAutomaticDebit Id_Prestamo
  """
  id_Prestamo: Int!

  """
  getClientAutomaticDebit Id_Moneda_Destino
  """
  id_Moneda_Destino: Int!
}

input getClientBankAccountInput {
  user: String!

  idBrand: Int!

  tenantId: String

  traceidentifier: String

  id_Cliente: Int!

  id_Prestamo: Int!
}

type getClientAutomaticDebit {
  """
  getClientAutomaticDebit Origen
  """
  origen: String!

  """
  getClientAutomaticDebit Id
  """
  id: Long!

  """
  getClientAutomaticDebit Id_Banco
  """
  id_Banco: Int!

  """
  getClientAutomaticDebit descripcion_banco
  """
  descripcion_banco: String!

  """
  getClientAutomaticDebit NumeroCuenta
  """
  numeroCuenta: String!

  """
  getClientAutomaticDebit FechaDebito
  """
  fechaDebito: String!

  """
  getClientAutomaticDebit Id_Cliente
  """
  id_Cliente: Long!

  """
  getClientAutomaticDebit Id_Moneda
  """
  id_Moneda: Int!

  """
  getClientAutomaticDebit Usuario
  """
  usuario: String!

  """
  getClientAutomaticDebit Id_Prestamo
  """
  id_Prestamo: Int!

  """
  getClientAutomaticDebit Id_Moneda_Destino
  """
  id_Moneda_Destino: Int!
}

input getClientAutomaticDebitInput {
  user: String!

  idBrand: Int!

  tenantId: String

  traceidentifier: String

  id_Cliente: Int!

  id_Prestamo: Int!

  proceso: String!
}

type terminsAndConditions {
  """
  terminsAndConditions terminsAndConditionsHtml
  """
  terminsAndConditionsHtml: String!
}

input terminsAndConditionsInput {
  user: String!

  idBrand: Int!

  tenantId: String

  traceidentifier: String

  styleDark: Boolean!
}

type listBanks {
  """
  listBanks id
  """
  id: Long

  """
  listBanks banco
  """
  banco: String

  """
  listBanks bit_SINPE
  """
  bit_SINPE: Short

  """
  listBanks p_Int_Sub_Origen
  """
  p_Int_Sub_Origen: Short

  """
  listBanks bit_Interno
  """
  bit_Interno: Short

  """
  listBanks tin_Length_SINPE
  """
  tin_Length_SINPE: Short

  """
  listBanks str_Mask_Interno
  """
  str_Mask_Interno: String

  """
  listBanks bit_Estado
  """
  bit_Estado: Boolean

  """
  listBanks fk_Suv_Mtr_Usuario
  """
  fk_Suv_Mtr_Usuario: Int

  """
  listBanks fk_Suv_Cat_Marca
  """
  fk_Suv_Cat_Marca: Short

  """
  listBanks subOrigen
  """
  subOrigen: Short

  """
  listBanks cODIGO_ACH
  """
  cODIGO_ACH: String
}

scalar Short

input listBanksInput {
  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

type CreditMutation {
  saveCreditFlowStep(saveCreditFlowStepInput: saveCreditFlowStepInput): saveCreditFlowStep

  saveCreditApplication(creditApplicationInputType: CreditApplicationInputType): saveCreditApplication

  saveCreditOperation(saveCreditOperationInput: saveCreditOperationInput): saveCreditOperation

  proccessPaymentList(proccessPaymentListInput: proccessPaymentListInput): proccessPaymentList
}

type saveCreditFlowStep {
  """
  saveCreditFlowStep MessageInfo
  """
  messageInfo: String!

  """
  saveCreditFlowStep Status
  """
  status: Int!

  """
  saveCreditFlowStep Result
  """
  result: String!
}

input saveCreditFlowStepInput {
  user: String!

  idBrand: Int!

  tenantId: String

  traceidentifier: String

  infoQuestion: [questionsDataListInput]!

  idLogUserRequest: Int!

  idUser: Int!

  currentStep: String!
}

input questionsDataListInput {
  idQuestionRequestCredit: Int!

  idOptionQuestionRequestCredit: Int

  createUser: String

  updateUser: String

  createDate: Date

  updateDate: Date

  identificator: String

  value: String

  active: Boolean

  controlType: String

  isCoreCatalogue: Boolean

  isBranchOfficeCatalogue: Boolean

  useValue: Boolean

  maximumAmount: String

  description: String

  valueCatalogue: String

  idIdentificatorCatalogue: String
}

"""
The `Date` scalar type represents a year, month and day in accordance with the [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) standard.
"""
scalar Date

type saveCreditApplication {
  """
  saveCreditApplication Pk_Suv_Log_Solicitud_Usuario
  """
  pk_Suv_Log_Solicitud_Usuario: Int!

  """
  saveCreditApplication Fk_Suv_Mtr_Usuario
  """
  fk_Suv_Mtr_Usuario: Int!

  """
  saveCreditApplication Usuario_Modificacion
  """
  usuario_Modificacion: String!

  """
  saveCreditApplication Fecha_Modificacion
  """
  fecha_Modificacion: DateTime!

  """
  saveCreditApplication Moneda_Prestamo
  """
  moneda_Prestamo: String!

  """
  saveCreditApplication Moneda_Escenario
  """
  moneda_Escenario: String!

  """
  saveCreditApplication Monto_Solicitado
  """
  monto_Solicitado: Decimal!

  """
  saveCreditApplication Pk_Pse_Cat_Promocion
  """
  pk_Pse_Cat_Promocion: Int!

  """
  saveCreditApplication Id_Producto
  """
  id_Producto: Int!

  """
  saveCreditApplication Plazo
  """
  plazo: String!

  """
  saveCreditApplication Descripcion_Promocion_Plazo
  """
  descripcion_Promocion_Plazo: String!

  """
  saveCreditApplication Tasa
  """
  tasa: String!

  """
  saveCreditApplication Cuota_Total
  """
  cuota_Total: String!

  """
  saveCreditApplication Comision_Desembolso
  """
  comision_Desembolso: String!

  """
  saveCreditApplication Tracto
  """
  tracto: Decimal!

  """
  saveCreditApplication Monto_Disponible
  """
  monto_Disponible: Decimal!

  """
  saveCreditApplication Monto_Minimo_Credito
  """
  monto_Minimo_Credito: Decimal!

  """
  saveCreditApplication Fecha_Pago
  """
  fecha_Pago: String!

  """
  saveCreditApplication currentStep
  """
  currentStep: String!

  """
  saveCreditApplication Status
  """
  status: Int

  """
  saveCreditApplication Message
  """
  message: String

  """
  saveCreditApplication Detail
  """
  detail: String
}

"""
The `DateTime` scalar type represents a date and time. `DateTime` expects timestamps to be formatted in accordance with the [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) standard.
"""
scalar DateTime

input CreditApplicationInputType {
  idUserRequest: Int!

  pkUser: Int!

  descPromotion: String!

  interestRate: String!

  symbolCurrency: String!

  descCurrency: String!

  selectedAmount: Decimal!

  idProduct: Int!

  idPromotion: Int!

  months: String!

  commisionPercentage: String!

  tractAmount: Decimal!

  minimunAmount: Decimal!

  paymentDate: String!

  paymentAmount: String!

  creditLimit: Decimal!

  currentStep: String!

  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

type saveCreditOperation {
  """
  saveCreditOperation idPrint
  """
  idPrint: Long

  """
  saveCreditOperation showFinalScreen
  """
  showFinalScreen: Boolean!

  """
  saveCreditOperation showOutSchedule
  """
  showOutSchedule: Boolean!
}

input saveCreditOperationInput {
  idUserRequest: Int!

  pkUser: Int!

  user: String!

  idBrand: Int!

  tenantId: String

  traceIdentifier: String
}

type proccessPaymentList {
  """
  proccessPaymentList Status
  """
  sTATUS: Short!

  """
  proccessPaymentList numero_Referencia_Interno
  """
  cODIGO_RECHAZO_SINPE: String!

  """
  proccessPaymentList numero_Referencia_Interno
  """
  mOTIVO_RECHAZO_SINPE: String!

  """
  proccessPaymentList numero_Referencia_Interno
  """
  mENSAJE_RESPUESTA: String!

  """
  proccessPaymentList numero_Referencia_Interno
  """
  mENSAJE_RESPUESTA_INTERNO: String!

  """
  proccessPaymentList numero_Referencia_Interno
  """
  nUMERO_REFERENCIA_INTERNO: String!

  """
  proccessPaymentList numero_Referencia_Interno
  """
  nUM_REF_SINPE: String!
}

input proccessPaymentListInput {
  user: String!

  idBrand: Int!

  tenantId: String

  traceidentifier: String

  id_Cliente: Int!

  identificacion: String!

  numeroCuentaOrigen: String!

  numeroCuentaDestino: String!

  id_Moneda: String!

  monto: Decimal!

  nombreCliente: String!

  descripcion: String!

  cuentaDestino: [CuentaDestino]!
}

input CuentaDestino {
  numeroCuentaDestino: String!

  idMonedaDestino: String!

  montoDestino: String!
}

schema {
  query: CreditQuery
  mutation: CreditMutation
}
