plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'dagger.hilt.android.plugin'
    id 'kotlin-kapt'
    id 'dexguard'
    id("com.apollographql.apollo3").version("3.3.0")
}

apply from: '../dependencies.gradle'

// gradle properties
def properties = new Properties()
properties.load(new FileInputStream(rootProject.file("gradle-custom.properties")))

android {
    compileSdk compile_sdk_version

    defaultConfig {
        minSdk min_sdk_version
        targetSdk target_sdk_version

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        production {
            minifyEnabled false
            shrinkResources false
            buildConfigField "String", "API_URL", System.env.PRODUCTION_API_URL ? "\"${System.env.PRODUCTION_API_URL}\"" : properties.apiUrl
            buildConfigField "String", "DATA_STORE_KEY", System.env.PRODUCTION_DATA_STORE_KEY ? "\"${System.env.PRODUCTION_DATA_STORE_KEY}\"" : properties.dataStoreKey
            buildConfigField "String", "DATA_STORE_BIOMETRIC_KEY", System.env.PRODUCTION_DATA_STORE_BIOMETRIC_KEY ? "\"${System.env.PRODUCTION_DATA_STORE_BIOMETRIC_KEY}\"" : properties.dataStoreBiometricKey
        }
        staging {
            testCoverageEnabled true
            buildConfigField "String", "API_URL", System.env.STAGING_API_URL ? "\"${System.env.STAGING_API_URL}\"" : properties.apiUrlStaging
            buildConfigField "String", "DATA_STORE_KEY", System.env.STAGING_DATA_STORE_KEY ? "\"${System.env.STAGING_DATA_STORE_KEY}\"" : properties.dataStoreKey
            buildConfigField "String", "DATA_STORE_BIOMETRIC_KEY", System.env.STAGING_DATA_STORE_BIOMETRIC_KEY ? "\"${System.env.STAGING_DATA_STORE_BIOMETRIC_KEY}\"" : properties.dataStoreBiometricKey
        }
        debug {
            testCoverageEnabled true
            buildConfigField "String", "API_URL", System.env.DEVELOPMENT_API_URL ? "\"${System.env.DEVELOPMENT_API_URL}\"" : properties.apiUrl
            buildConfigField "String", "DATA_STORE_KEY", System.env.DEVELOPMENT_DATA_STORE_KEY ? "\"${System.env.DEVELOPMENT_DATA_STORE_KEY}\"" : properties.dataStoreKey
            buildConfigField "String", "DATA_STORE_BIOMETRIC_KEY", System.env.DEVELOPMENT_DATA_STORE_BIOMETRIC_KEY ? "\"${System.env.DEVELOPMENT_DATA_STORE_BIOMETRIC_KEY}\"" : properties.dataStoreBiometricKey
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
        freeCompilerArgs += "-Xopt-in=kotlin.RequiresOptIn"
    }
}

apollo {
    service("security") {
        sourceFolder.set("com/multimoney/multimoney/security")
        packageName.set("com.multimoney.data.networking.security.apollomodel")
        generateOptionalOperationVariables.set(false)
    }
    service("balances") {
        sourceFolder.set("com/multimoney/multimoney/balances")
        packageName.set("com.multimoney.data.networking.balances.apollomodel")
        generateOptionalOperationVariables.set(false)
    }
    service("credit") {
        sourceFolder.set("com/multimoney/multimoney/credit")
        packageName.set("com.multimoney.data.networking.credit.apollomodel")
        generateOptionalOperationVariables.set(false)
    }
}

dependencies {

    implementation project(path: ':domain')

    // Common
    implementation common.serialization_json

    // Room
    implementation room.runtime
    kapt room.compiler
    implementation room.ktx
    testImplementation room.testing

    // Hilt
    implementation hilt.android
    kapt hilt.compiler

    // Preferences
    implementation preferences.data_store

    // Coroutines
    implementation coroutines.android

    // Apollo
    implementation apollo.runtime
    implementation apollo.cache
    implementation apollo.cache_sqlite

    // Cognito
    api cognito.core
    api cognito.auth

    // OkHttp3
    implementation okhttp3.interceptor

    // Gson
    api gson.gson

    // Common Test
    testImplementation common_test.junit
    androidTestImplementation common_test.ext_junit
    androidTestImplementation common_test.espresso
    testImplementation common_test.robolectric
    testImplementation common_test.mockito_core
}