mutation GlobalRequest($pkUser: Int!, $status: Int!, $idProfessionType: Int!, $idAddressLevel1: Long!,
    $idAddressLevel2: Long!,
    $birthdate: Date!,
    $expirationDate: Date!,
    $idGenre: Long!,
    $idMaritalStatus: Long!,
    $nameCompany: String,
    $aboutCompany: String!,
    $institutionPension: String!,
    $idAddressLevel3: Long!, $idEconomicActivity: Long!, $income: Decimal!, $addressDetail: String!
    $isPEP: Boolean!, $user: String!, $idBrand: Int!, $currentStep: String!, $specifiesIncomeSource: String!, $listBeneficiaries: [beneficiarieList]) {
    globalRequest(globalRequestInput: {
        pkUser: $pkUser
        status: $status
        idProfessionType: $idProfessionType,
        birthdate:$birthdate,
        expirationDate:$expirationDate,
        idGenre:$idGenre,
        idMaritalStatus: $idMaritalStatus,
        institutionPesion: $institutionPension,
        nameCompany: $nameCompany,
        aboutCompany : $aboutCompany,
        idAddressLevel1 : $idAddressLevel1
        idAddressLevel2 : $idAddressLevel2
        idAddressLevel3 : $idAddressLevel3
        idEconomicActivity : $idEconomicActivity
        income : $income
        addressDetail: $addressDetail
        isPEP: $isPEP
        user: $user
        idBrand: $idBrand
        currentStep: $currentStep
        specifiesIncomeSource: $specifiesIncomeSource,
        listBeneficiaries: $listBeneficiaries
    }) {
        result {
            idGlobalRequest
            accountExists
            idSysdeRequest
        }
    }
}