mutation ChangeEmail($pkUser:Long!, $idClient:Long!, $identification:String!, $email:String!,$registerId:Int!,$changeUser:Boolean!,$idBrand:Int!,$user:String!){
    changeEmail(
        changeEmailInputType: {
            pkUser: $pkUser,
            idClient: $idClient,
            identification: $identification,
            email: $email,
            registerId: $registerId,
            changeUser: $changeUser
            user: $user,
            idBrand: $idBrand
        }
    ) {
        status
    }
}