mutation UserValidation($email:String!, $currentStep:String!, $idBrand:Int!, $idDocument:Long!, $identification:String!, $firtName:String!,$secondName:String, $firtSurname:String! $secondSurname:String, $deviceId:String!){
  userValidation(
    userValidationInput: {
      email: $email
      currentStep: $currentStep
      idBrand: $idBrand
      idDocument: $idDocument
      identification: $identification
      firtName: $firtName
      secondName:$secondName
      firtSurname: $firtSurname
      secondSurname: $secondSurname
      deviceId: $deviceId
    }
  ) {
    pkUser
    userName
    email
    phoneNumber
    fullName
    firstName
    secondName
    lastName
    secondLastName
    contactMeans
    nationality
    identification
    countryCode
    currentStep
    userStatus
    isNewUser
    maskedMail
    maskedPhoneNumber
    message
    status,
    detail
  }
}