mutation UserPhoneMobileSave($idBrand:Int!, $idWalletCard:String!, $manufacture:String!, $pkUser:Long!, $serialNumber:String!, $user:String!){
  userPhoneMobileSave(
    userPhoneMobileSaveInput: {
      idBrand: $idBrand
      idWalletCard: $idWalletCard,
      manufacture: $manufacture,
      pkUser: $pkUser,
      serialNumber: $serialNumber,
      user: $user
    }
  ) {
    pK_SUV_LOG_USUARIO_EVENTO_MOBILE
    fK_SUV_MTR_USUARIO
    plataforma
    uuid
    version_Dispositivo
    manofactura
    nombre_Dispositivo
    numero_Serie
    direccion_Ip
    latitud
    longitud
    tokenNotificationsPush
    dISPOSITIVO_TARJETA
    iD_BILLETERA_TARJETA
    status
    message
    detail
  }
}